#!/usr/bin/env python3
"""Hello, penguins! 词表、课文、音形与学单词例句。"""

from __future__ import annotations

ACCENT = "#00838f"
ACCENT_DARK = "#004d40"
ACCENT_LIGHT = "#4dd0e1"
BG_LIGHT = "#e0f7fa"
WILD = "#01579b"

WORDS = [
    ("Penguin", "企鹅", "Hello, penguin!", "🐧"),
    ("On the ice", "在冰上", "These penguins live on the ice.", "🧊"),
    ("On the beach", "在沙滩上", "This kind lives on the beach.", "🏖️"),
    ("In the forest", "在森林里", "These penguins live in the forest.", "🌲"),
    ("Huddle", "挤成一团", "They huddle to keep warm.", "🤗"),
    ("Shuffle", "小步走", "They can shuffle.", "🚶"),
    ("Slide", "滑行", "They can slide.", "🛷"),
    ("Swim", "游泳", "They use their wings to swim.", "🏊"),
    ("Big", "大的", "Some kinds of penguins are big.", "🐘"),
    ("Small", "小的", "Some are small.", "🐭"),
    ("Fancy", "花哨的", "Some are fancy.", "✨"),
    ("Plain", "朴素的", "And some are plain.", "◻️"),
    ("Cold", "寒冷的", "It's cold!", "❄️"),
    ("Keep warm", "保暖", "They huddle to keep warm.", "🧣"),
    ("Kind", "种类", "This kind lives on the beach.", "🏷️"),
    ("Many kinds of", "许多种", "There are many kinds of penguins.", "📚"),
    ("Make", "建造", "They make nests.", "🛠️"),
    ("Nest", "巢", "They make nests in the dirt and sand.", "🪺"),
    ("Dirt", "泥土", "They make nests in the dirt.", "🟤"),
    ("Sand", "沙子", "They make nests in the sand.", "🏜️"),
    ("Waddle", "摇摇摆摆地走", "They waddle over tree roots.", "🦆"),
    ("Tree root", "树根", "They waddle over tree roots.", "🌳"),
    ("Can", "能", "They can shuffle.", "✅"),
    ("Can't", "不能", "Penguins can't fly.", "🚫"),
    ("Use", "使用", "They use their wings to swim.", "🔧"),
    ("Wing", "翅膀", "They use their wings to swim.", "🪽"),
    ("Splash", "溅水", "Splash!", "💦"),
    ("Go fishing", "去捕鱼", "It's time to go fishing!", "🎣"),
    ("Go back on land", "回到陆地上", "It's time to go back on land.", "🏝️"),
]

STORY = [
    ("Hello, penguin!", "你好，企鹅！"),
    ("It's cold! These penguins live on the ice.", "好冷！这些企鹅住在冰上。"),
    ("They huddle to keep warm.", "它们挤成一团来保暖。"),
    ("There are many kinds of penguins.", "企鹅有许多种类。"),
    ("This kind lives on the beach.", "这种企鹅住在沙滩上。"),
    ("They make nests in the dirt and sand.", "它们在泥土和沙子里筑巢。"),
    ("These penguins live in the forest.", "这些企鹅住在森林里。"),
    ("They waddle over tree roots.", "它们摇摇摆摆地走过树根。"),
    ("Some kinds of penguins are big.", "有的企鹅很大。"),
    ("Some are small.", "有的很小。"),
    ("Some are fancy.", "有的很花哨。"),
    ("And some are plain.", "有的很朴素。"),
    ("Penguins can't fly.", "企鹅不会飞。"),
    ("But they can shuffle.", "但是它们能小步走。"),
    ("And they can slide.", "它们还能滑行。"),
    ("They use their wings to swim.", "它们用翅膀游泳。"),
    ("Splash!", "扑通！"),
    ("It's time to go fishing!", "该去捕鱼了！"),
    ("This penguin gets a yummy fish.", "这只企鹅抓到一条好吃的鱼。"),
    ("After a swim, it's time to go back on land.", "游完泳，该回到陆地上了。"),
    ("Hello, penguin!", "你好，企鹅！"),
]

# 课文句 → 优先使用的真实照片（species / action）
STORY_PHOTO = {
    2: "emperor-ice.jpg",
    3: "emperor-huddle.jpg",
    5: "magellanic-beach.jpg",
    6: "magellanic-nest.jpg",
    7: "snares-forest.jpg",
    8: "snares-roots.jpg",
    9: "emperor-big.jpg",
    10: "fairy-small.jpg",
    11: "rockhopper-fancy.jpg",
    12: "adelie-plain.jpg",
    14: "chinstrap-shuffle.jpg",
    15: "penguin-slide.jpg",
    16: "penguin-swim.jpg",
    17: "penguin-splash.jpg",
    18: "humboldt-fish.jpg",
    19: "penguin-fish.jpg",
    20: "gentoo-land.jpg",
}

SAY = {
    "Penguin": {
        "ex": {"en": "I draw a penguin.", "zh": "我画一只企鹅。"},
        "sort": {"en": "This toy is a penguin.", "zh": "这个玩具是企鹅。"},
        "en": "We see a penguin book.",
        "zh": "我们看见一本企鹅书。",
    },
    "On the ice": {
        "ex": {"en": "The cup is on the ice.", "zh": "杯子在冰上。"},
        "sort": {"en": "We skate on the ice.", "zh": "我们在冰上滑冰。"},
        "en": "Do not run on the ice.",
        "zh": "不要在冰上跑。",
    },
    "On the beach": {
        "ex": {"en": "We play on the beach.", "zh": "我们在沙滩上玩。"},
        "sort": {"en": "Shells are on the beach.", "zh": "贝壳在沙滩上。"},
        "en": "I sit on the beach.",
        "zh": "我坐在沙滩上。",
    },
    "In the forest": {
        "ex": {"en": "Birds live in the forest.", "zh": "鸟住在森林里。"},
        "sort": {"en": "We walk in the forest.", "zh": "我们在森林里走。"},
        "en": "It is quiet in the forest.",
        "zh": "森林里很安静。",
    },
    "Huddle": {
        "ex": {"en": "We huddle in the rain.", "zh": "下雨时我们挤在一起。"},
        "sort": {"en": "The team can huddle.", "zh": "队员可以围成一团。"},
        "en": "Puppies huddle to sleep.",
        "zh": "小狗挤在一起睡觉。",
    },
    "Shuffle": {
        "ex": {"en": "I shuffle my feet.", "zh": "我拖着脚走。"},
        "sort": {"en": "Please shuffle the cards.", "zh": "请洗牌。"},
        "en": "We shuffle in a line.",
        "zh": "我们排成一列小步走。",
    },
    "Slide": {
        "ex": {"en": "I slide on the mat.", "zh": "我在垫子上滑。"},
        "sort": {"en": "The box can slide.", "zh": "盒子能滑。"},
        "en": "Kids slide at the park.",
        "zh": "孩子们在公园滑滑梯。",
    },
    "Swim": {
        "ex": {"en": "I swim in the pool.", "zh": "我在游泳池游泳。"},
        "sort": {"en": "Fish swim in the lake.", "zh": "鱼在湖里游。"},
        "en": "We swim on Saturday.",
        "zh": "我们星期六游泳。",
    },
    "Big": {
        "ex": {"en": "This bag is big.", "zh": "这个包很大。"},
        "sort": {"en": "The bus is big.", "zh": "公交车很大。"},
        "en": "I want a big apple.",
        "zh": "我想要一个大苹果。",
    },
    "Small": {
        "ex": {"en": "The ant is small.", "zh": "蚂蚁很小。"},
        "sort": {"en": "I have a small cup.", "zh": "我有一个小杯子。"},
        "en": "This button is small.",
        "zh": "这颗纽扣很小。",
    },
    "Fancy": {
        "ex": {"en": "Her hat is fancy.", "zh": "她的帽子很花哨。"},
        "sort": {"en": "This cake looks fancy.", "zh": "这块蛋糕看起来很花哨。"},
        "en": "He wears a fancy tie.",
        "zh": "他戴着花哨的领带。",
    },
    "Plain": {
        "ex": {"en": "My shirt is plain.", "zh": "我的衬衫很朴素。"},
        "sort": {"en": "I like plain rice.", "zh": "我喜欢白米饭。"},
        "en": "The wall is plain.",
        "zh": "墙是素净的。",
    },
    "Cold": {
        "ex": {"en": "The water is cold.", "zh": "水是冷的。"},
        "sort": {"en": "I feel cold.", "zh": "我觉得冷。"},
        "en": "Winter is cold.",
        "zh": "冬天很冷。",
    },
    "Keep warm": {
        "ex": {"en": "A coat can keep warm.", "zh": "外套能保暖。"},
        "sort": {"en": "Hats keep warm in winter.", "zh": "冬天帽子能保暖。"},
        "en": "We keep warm by the fire.",
        "zh": "我们靠火堆保暖。",
    },
    "Kind": {
        "ex": {"en": "What kind of fruit?", "zh": "哪种水果？"},
        "sort": {"en": "This kind is sweet.", "zh": "这种是甜的。"},
        "en": "I like this kind.",
        "zh": "我喜欢这种。",
    },
    "Many kinds of": {
        "ex": {"en": "I see many kinds of books.", "zh": "我看见许多种书。"},
        "sort": {"en": "The zoo has many kinds of birds.", "zh": "动物园有许多种鸟。"},
        "en": "We try many kinds of soup.",
        "zh": "我们试许多种汤。",
    },
    "Make": {
        "ex": {"en": "I make a card.", "zh": "我做一张卡片。"},
        "sort": {"en": "We make a cake.", "zh": "我们做蛋糕。"},
        "en": "They make a paper boat.",
        "zh": "他们折纸船。",
    },
    "Nest": {
        "ex": {"en": "The bird has a nest.", "zh": "鸟有一个巢。"},
        "sort": {"en": "I see a nest in the tree.", "zh": "我看见树上有个巢。"},
        "en": "Do not touch the nest.",
        "zh": "不要碰那个巢。",
    },
    "Dirt": {
        "ex": {"en": "My shoes have dirt.", "zh": "我的鞋上有土。"},
        "sort": {"en": "We dig in the dirt.", "zh": "我们在土里挖。"},
        "en": "Wash the dirt off.",
        "zh": "把土洗掉。",
    },
    "Sand": {
        "ex": {"en": "Sand is on my toes.", "zh": "沙子在我脚趾上。"},
        "sort": {"en": "We build with sand.", "zh": "我们用沙子堆东西。"},
        "en": "The box is full of sand.",
        "zh": "盒子里装满沙子。",
    },
    "Waddle": {
        "ex": {"en": "Ducks waddle to the pond.", "zh": "鸭子摇摇摆摆走向池塘。"},
        "sort": {"en": "The baby can waddle.", "zh": "宝宝会摇摇摆摆走。"},
        "en": "I waddle in big boots.",
        "zh": "我穿着大靴子摇摇摆摆走。",
    },
    "Tree root": {
        "ex": {"en": "A tree root is in the path.", "zh": "路上有一条树根。"},
        "sort": {"en": "Do not trip on the tree root.", "zh": "别被树根绊倒。"},
        "en": "The tree root is thick.",
        "zh": "这条树根很粗。",
    },
    "Can": {
        "ex": {"en": "I can hop.", "zh": "我能跳。"},
        "sort": {"en": "She can read.", "zh": "她能读。"},
        "en": "We can help.",
        "zh": "我们能帮忙。",
    },
    "Can't": {
        "ex": {"en": "I can't fly.", "zh": "我不能飞。"},
        "sort": {"en": "He can't reach the shelf.", "zh": "他够不到架子。"},
        "en": "We can't eat in class.",
        "zh": "我们不能在课上吃东西。",
    },
    "Use": {
        "ex": {"en": "I use a pencil.", "zh": "我用铅笔。"},
        "sort": {"en": "We use spoons.", "zh": "我们用勺子。"},
        "en": "Please use the door.",
        "zh": "请走门。",
    },
    "Wing": {
        "ex": {"en": "The bird has a wing.", "zh": "鸟有翅膀。"},
        "sort": {"en": "I see one red wing.", "zh": "我看见一只红翅膀。"},
        "en": "A plane has a wing.",
        "zh": "飞机有机翼。",
    },
    "Splash": {
        "ex": {"en": "I splash in the tub.", "zh": "我在浴缸里溅水。"},
        "sort": {"en": "The dog can splash.", "zh": "狗会溅水。"},
        "en": "Don't splash my book.",
        "zh": "别把水溅到我的书上。",
    },
    "Go fishing": {
        "ex": {"en": "We go fishing with Dad.", "zh": "我们和爸爸去钓鱼。"},
        "sort": {"en": "They go fishing at the lake.", "zh": "他们去湖边钓鱼。"},
        "en": "I want to go fishing.",
        "zh": "我想去钓鱼。",
    },
    "Go back on land": {
        "ex": {"en": "The boat must go back on land.", "zh": "船必须回到岸上。"},
        "sort": {"en": "After class we go back on land.", "zh": "下课后我们回到岸上。"},
        "en": "Crabs go back on land.",
        "zh": "螃蟹回到陆地上。",
    },
}


def b(text, hint, combo=False, friends=None):
    o = {"text": text, "hint": hint, "combo": combo}
    if combo:
        o["friends"] = friends or []
    return o


SOUND_BOXES = {
    "Penguin": [
        b("p", "/p/"),
        b("e", "短 e"),
        b("ng", "/ng/", True, ["penguin", "sing", "long", "king"]),
        b("u", "短 i 发 /ɪ/"),
        b("i", "短 i"),
        b("n", "/n/"),
    ],
    "On the ice": [
        b("o", "短 o"),
        b("n", "/n/"),
        b(" ", "空格"),
        b("th", "/th/", True, ["the", "this", "that"]),
        b("e", "弱读 /ə/"),
        b(" ", "空格"),
        b("i", "长 /ī/"),
        b("ce", "/s/", True, ["ice", "nice", "rice"]),
    ],
    "On the beach": [
        b("o", "短 o"),
        b("n", "/n/"),
        b(" ", "空格"),
        b("th", "/th/", True, ["the", "this", "that"]),
        b("e", "弱读 /ə/"),
        b(" ", "空格"),
        b("b", "/b/"),
        b("ea", "发 /ē/", True, ["beach", "eat", "sea", "read"]),
        b("ch", "/ch/", True, ["beach", "chip", "lunch"]),
    ],
    "In the forest": [
        b("i", "短 i"),
        b("n", "/n/"),
        b(" ", "空格"),
        b("th", "/th/", True, ["the", "this", "that"]),
        b("e", "弱读 /ə/"),
        b(" ", "空格"),
        b("f", "/f/"),
        b("o", "短 o"),
        b("r", "/r/"),
        b("e", "弱读 /ə/"),
        b("st", "/st/", True, ["forest", "stop", "best"]),
    ],
    "Huddle": [
        b("h", "/h/"),
        b("u", "短 u"),
        b("dd", "/d/"),
        b("le", "词尾 -le", True, ["huddle", "apple", "little"]),
    ],
    "Shuffle": [
        b("sh", "/sh/", True, ["shuffle", "ship", "fish"]),
        b("u", "短 u"),
        b("ff", "/f/"),
        b("le", "词尾 -le", True, ["shuffle", "apple", "little"]),
    ],
    "Slide": [
        b("s", "/s/"),
        b("l", "/l/"),
        b("i", "长 /ī/"),
        b("de", "/d/", True, ["slide", "ride", "hide"]),
    ],
    "Swim": [
        b("sw", "/sw/", True, ["swim", "swing", "sweet"]),
        b("i", "短 i"),
        b("m", "/m/"),
    ],
    "Big": [
        b("b", "/b/"),
        b("i", "短 i"),
        b("g", "/g/"),
    ],
    "Small": [
        b("s", "/s/"),
        b("m", "/m/"),
        b("all", "/ôl/", True, ["small", "ball", "tall", "call"]),
    ],
    "Fancy": [
        b("f", "/f/"),
        b("a", "短 a"),
        b("n", "/n/"),
        b("c", "/s/"),
        b("y", "词尾 y /ē/"),
    ],
    "Plain": [
        b("p", "/p/"),
        b("l", "/l/"),
        b("ai", "长 /ā/", True, ["plain", "rain", "wait", "paint"]),
        b("n", "/n/"),
    ],
    "Cold": [
        b("c", "/k/"),
        b("o", "长 /ō/"),
        b("ld", "/ld/", True, ["cold", "gold", "old"]),
    ],
    "Keep warm": [
        b("k", "/k/"),
        b("ee", "长 e", True, ["keep", "see", "tree", "need"]),
        b("p", "/p/"),
        b(" ", "空格"),
        b("w", "/w/"),
        b("ar", "/or/", True, ["warm", "war", "warn"]),
        b("m", "/m/"),
    ],
    "Kind": [
        b("k", "/k/"),
        b("i", "长 /ī/"),
        b("n", "/n/"),
        b("d", "/d/"),
    ],
    "Many kinds of": [
        b("m", "/m/"),
        b("a", "短 a"),
        b("n", "/n/"),
        b("y", "词尾 y /ē/"),
        b(" ", "空格"),
        b("k", "/k/"),
        b("i", "长 /ī/"),
        b("nds", "/ndz/"),
        b(" ", "空格"),
        b("o", "短 o"),
        b("f", "/f/"),
    ],
    "Make": [
        b("m", "/m/"),
        b("a", "长 /ā/"),
        b("ke", "/k/", True, ["make", "cake", "lake"]),
    ],
    "Nest": [
        b("n", "/n/"),
        b("e", "短 e"),
        b("st", "/st/", True, ["nest", "best", "stop"]),
    ],
    "Dirt": [
        b("d", "/d/"),
        b("ir", "/ər/", True, ["dirt", "bird", "girl", "first"]),
        b("t", "/t/"),
    ],
    "Sand": [
        b("s", "/s/"),
        b("a", "短 a"),
        b("n", "/n/"),
        b("d", "/d/"),
    ],
    "Waddle": [
        b("w", "/w/"),
        b("a", "短 o 发 /ɒ/"),
        b("dd", "/d/"),
        b("le", "词尾 -le", True, ["waddle", "apple", "little"]),
    ],
    "Tree root": [
        b("t", "/t/"),
        b("r", "/r/"),
        b("ee", "长 e", True, ["tree", "see", "green", "need"]),
        b(" ", "空格"),
        b("r", "/r/"),
        b("oo", "长 /oo/", True, ["root", "food", "moon", "room"]),
        b("t", "/t/"),
    ],
    "Can": [
        b("c", "/k/"),
        b("a", "短 a"),
        b("n", "/n/"),
    ],
    "Can't": [
        b("c", "/k/"),
        b("a", "短 a"),
        b("n", "/n/"),
        b("'", "撇号"),
        b("t", "/t/"),
    ],
    "Use": [
        b("u", "长 /ū/ 像 you"),
        b("se", "/z/", True, ["use", "these", "please"]),
    ],
    "Wing": [
        b("w", "/w/"),
        b("i", "短 i"),
        b("ng", "/ng/", True, ["wing", "sing", "long", "king"]),
    ],
    "Splash": [
        b("s", "/s/"),
        b("p", "/p/"),
        b("l", "/l/"),
        b("a", "短 a"),
        b("sh", "/sh/", True, ["splash", "ship", "fish"]),
    ],
    "Go fishing": [
        b("g", "/g/"),
        b("o", "长 /ō/", True, ["go", "no", "so"]),
        b(" ", "空格"),
        b("f", "/f/"),
        b("i", "短 i"),
        b("sh", "/sh/", True, ["fish", "ship", "wish"]),
        b("ing", "/ing/", True, ["fishing", "sing", "jumping"]),
    ],
    "Go back on land": [
        b("g", "/g/"),
        b("o", "长 /ō/", True, ["go", "no", "so"]),
        b(" ", "空格"),
        b("b", "/b/"),
        b("a", "短 a"),
        b("ck", "/k/", True, ["back", "duck", "kick"]),
        b(" ", "空格"),
        b("o", "短 o"),
        b("n", "/n/"),
        b(" ", "空格"),
        b("l", "/l/"),
        b("a", "短 a"),
        b("n", "/n/"),
        b("d", "/d/"),
    ],
}
