#!/usr/bin/env python3
"""Generate verbs-data.js with 80 irregular verbs and example sentences."""
import json

VERBS = [
    {"id":"be","base":"be","past":"was / were","pp":"been","cn":"是；在","ipa":"/biː/","emoji":"🧍",
     "present":{"en":"I am always ready to help my classmates.","cn":"我总是乐于帮助同学。"},
     "past":{"en":"She was very kind to the new student yesterday.","cn":"她昨天对新同学非常友善。"},
     "perfect":{"en":"He has been a member of the school team for two years.","cn":"他加入校队已经两年了。"}},
    {"id":"beat","base":"beat","past":"beat","pp":"beaten","cn":"打败；敲打","ipa":"/biːt/","emoji":"🥁",
     "present":{"en":"Our team often beats strong rivals in practice.","cn":"我们队在训练中常战胜强敌。"},
     "past":{"en":"He beat the school record in the 100-metre race.","cn":"他打破了学校百米纪录。"},
     "perfect":{"en":"She has beaten her personal best three times this term.","cn":"本学期她已三次刷新个人最好成绩。"}},
    {"id":"become","base":"become","past":"became","pp":"become","cn":"变成；成为","ipa":"/bɪˈkʌm/","emoji":"🦋",
     "present":{"en":"Hard work becomes a good habit if you keep trying.","cn":"坚持努力就会变成好习惯。"},
     "past":{"en":"He became the monitor of our class last year.","cn":"他去年当上了我们班的班长。"},
     "perfect":{"en":"English has become my favourite subject since Grade 8.","cn":"自八年级起英语成了我最喜欢的科目。"}},
    {"id":"begin","base":"begin","past":"began","pp":"begun","cn":"开始","ipa":"/bɪˈɡɪn/","emoji":"🚀",
     "present":{"en":"Our English class begins at eight every morning.","cn":"我们的英语课每天早上八点开始。"},
     "past":{"en":"The concert began with a beautiful song.","cn":"音乐会以一首优美的歌曲开场。"},
     "perfect":{"en":"The project has begun, so we must work as a team.","cn":"项目已经启动，我们必须团队合作。"}},
    {"id":"break","base":"break","past":"broke","pp":"broken","cn":"打破；弄坏","ipa":"/breɪk/","emoji":"💔",
     "present":{"en":"Be careful not to break the glass on the desk.","cn":"小心别打碎桌上的玻璃杯。"},
     "past":{"en":"He broke his arm when he fell off his bike.","cn":"他从自行车上摔下来时手臂骨折了。"},
     "perfect":{"en":"The old bridge has been broken for months.","cn":"那座旧桥已经坏了好几个月了。"}},
    {"id":"bring","base":"bring","past":"brought","pp":"brought","cn":"带来","ipa":"/brɔːt/","emoji":"🎁",
     "present":{"en":"Please bring your notebook to every English lesson.","cn":"每次英语课请带上笔记本。"},
     "past":{"en":"She brought some flowers to thank the teacher.","cn":"她带了些花来感谢老师。"},
     "perfect":{"en":"Technology has brought great changes to our daily life.","cn":"科技给我们的日常生活带来了巨大变化。"}},
    {"id":"build","base":"build","past":"built","pp":"built","cn":"建造","ipa":"/bɪld/","emoji":"🏗️",
     "present":{"en":"We build good friendships through trust and care.","cn":"我们通过信任与关心建立友谊。"},
     "past":{"en":"They built a model of the Great Wall in art class.","cn":"他们在美术课上搭建了长城模型。"},
     "perfect":{"en":"Our school has built a new library since last year.","cn":"自去年起学校新建了一座图书馆。"}},
    {"id":"buy","base":"buy","past":"bought","pp":"bought","cn":"买","ipa":"/bɔːt/","emoji":"🛒",
     "present":{"en":"I usually buy snacks after school with my pocket money.","cn":"我通常用零花钱放学后买零食。"},
     "past":{"en":"He bought a dictionary to prepare for the exam.","cn":"他买了一本词典来备考。"},
     "perfect":{"en":"My parents have bought me many books about science.","cn":"父母给我买过许多科学类书籍。"}},
    {"id":"can","base":"can","past":"could","pp":"—","cn":"能；会","ipa":"/kæn/","emoji":"💪","special":True,
     "present":{"en":"I can swim fifty metres without stopping.","cn":"我能一口气游五十米。"},
     "past":{"en":"When I was five, I could count to one hundred.","cn":"我五岁时能数到一百。"},
     "perfect":{"en":"With practice, you could have done better in the test.","cn":"多练习的话，你本可以在考试中做得更好。"}},
    {"id":"catch","base":"catch","past":"caught","pp":"caught","cn":"抓住；赶上","ipa":"/kætʃ/","emoji":"🤲",
     "present":{"en":"Run fast or you will not catch the school bus.","cn":"快跑，否则赶不上校车。"},
     "past":{"en":"The goalkeeper caught the ball at the last moment.","cn":"守门员在最后一刻接住了球。"},
     "perfect":{"en":"I have caught a bad cold, so I stayed at home.","cn":"我得了重感冒，所以待在家里。"}},
    {"id":"choose","base":"choose","past":"chose","pp":"chosen","cn":"选择","ipa":"/tʃuːz/","emoji":"✅",
     "present":{"en":"You can choose any topic you like for the speech.","cn":"演讲题目你可以任选喜欢的。"},
     "past":{"en":"She chose art as her favourite subject last term.","cn":"上学期她选了美术作为最喜欢的科目。"},
     "perfect":{"en":"He has chosen to study harder for his dream university.","cn":"他为圆梦大学已决定更加努力学习。"}},
    {"id":"come","base":"come","past":"came","pp":"come","cn":"来","ipa":"/kʌm/","emoji":"👋",
     "present":{"en":"My best friend comes to school with me every day.","cn":"我最好的朋友每天和我一起来上学。"},
     "past":{"en":"A famous writer came to our school last month.","cn":"一位著名作家上个月来我们学校了。"},
     "perfect":{"en":"Spring has come, and the flowers have bloomed.","cn":"春天来了，花儿都开了。"}},
    {"id":"cost","base":"cost","past":"cost","pp":"cost","cn":"花费","ipa":"/kɒst/","emoji":"💰",
     "present":{"en":"This dictionary costs thirty yuan in the bookshop.","cn":"这本词典在书店卖三十元。"},
     "past":{"en":"The school trip cost each student fifty yuan.","cn":"这次研学每位学生花了五十元。"},
     "perfect":{"en":"The repair has cost us a lot of time and effort.","cn":"这次修理耗费了我们大量时间和精力。"}},
    {"id":"cut","base":"cut","past":"cut","pp":"cut","cn":"切；剪","ipa":"/kʌt/","emoji":"✂️",
     "present":{"en":"Please cut the paper along the dotted line.","cn":"请沿虚线剪开纸张。"},
     "past":{"en":"He cut his finger while cooking dinner.","cn":"他做晚饭时割伤了手指。"},
     "perfect":{"en":"We have cut down on plastic bags at school.","cn":"我们在学校已减少使用塑料袋。"}},
    {"id":"do","base":"do","past":"did","pp":"done","cn":"做","ipa":"/duː/","emoji":"✍️",
     "present":{"en":"I do my homework before dinner every evening.","cn":"我每晚晚饭前做作业。"},
     "past":{"en":"We did a science experiment in the lab yesterday.","cn":"我们昨天在实验室做了科学实验。"},
     "perfect":{"en":"Have you done your part of the group project?","cn":"小组项目中你负责的部分做完了吗？"}},
    {"id":"draw","base":"draw","past":"drew","pp":"drawn","cn":"画；拉","ipa":"/drɔː/","emoji":"🎨",
     "present":{"en":"She draws beautiful pictures in her sketchbook.","cn":"她在素描本上画漂亮的画。"},
     "past":{"en":"He drew a map to help tourists find the way.","cn":"他画了一张地图帮游客找路。"},
     "perfect":{"en":"The artist has drawn attention with her new exhibition.","cn":"这位艺术家的新展览引起了广泛关注。"}},
    {"id":"drink","base":"drink","past":"drank","pp":"drunk","cn":"喝","ipa":"/drɪŋk/","emoji":"🥤",
     "present":{"en":"Drink enough water after exercise every day.","cn":"每天运动后要多喝水。"},
     "past":{"en":"We drank hot milk to keep warm in winter.","cn":"冬天我们喝热牛奶保暖。"},
     "perfect":{"en":"He has drunk two cups of coffee to stay awake.","cn":"为了提神他已喝了两杯咖啡。"}},
    {"id":"drive","base":"drive","past":"drove","pp":"driven","cn":"驾驶","ipa":"/draɪv/","emoji":"🚗",
     "present":{"en":"My father drives me to school on rainy days.","cn":"下雨天爸爸开车送我去学校。"},
     "past":{"en":"She drove carefully on the icy road last winter.","cn":"去年冬天她在结冰的路上小心驾驶。"},
     "perfect":{"en":"Hard work has driven him to success step by step.","cn":"勤奋一步步推动他走向成功。"}},
    {"id":"eat","base":"eat","past":"ate","pp":"eaten","cn":"吃","ipa":"/iːt/","emoji":"🍽️",
     "present":{"en":"We eat lunch in the school canteen at noon.","cn":"我们中午在学校食堂吃午饭。"},
     "past":{"en":"They ate dumplings during the Spring Festival.","cn":"春节期间他们吃了饺子。"},
     "perfect":{"en":"I have eaten too much junk food this week.","cn":"这周我垃圾食品吃太多了。"}},
    {"id":"fall","base":"fall","past":"fell","pp":"fallen","cn":"落下；跌倒","ipa":"/fɔːl/","emoji":"🍂",
     "present":{"en":"Leaves fall from the trees in autumn.","cn":"秋天树叶从树上落下。"},
     "past":{"en":"He fell off the ladder and hurt his leg.","cn":"他从梯子上摔下来伤了腿。"},
     "perfect":{"en":"Prices have fallen since the new shop opened.","cn":"新商店开业后价格已经下降了。"}},
    {"id":"feel","base":"feel","past":"felt","pp":"felt","cn":"感觉","ipa":"/fiːl/","emoji":"💭",
     "present":{"en":"I feel happy when I help others.","cn":"帮助别人时我感到开心。"},
     "past":{"en":"She felt nervous before the English speech contest.","cn":"英语演讲比赛前她感到紧张。"},
     "perfect":{"en":"We have felt proud of our team's progress.","cn":"我们为团队的进步感到自豪。"}},
    {"id":"fight","base":"fight","past":"fought","pp":"fought","cn":"打架；奋斗","ipa":"/faɪt/","emoji":"🥊",
     "present":{"en":"We should fight for our dreams, not give up easily.","cn":"我们应该为梦想奋斗，不轻易放弃。"},
     "past":{"en":"The soldiers fought bravely to protect their country.","cn":"战士们英勇保卫祖国。"},
     "perfect":{"en":"Scientists have fought against the disease for years.","cn":"科学家们多年来一直在与疾病抗争。"}},
    {"id":"find","base":"find","past":"found","pp":"found","cn":"找到；发现","ipa":"/faʊnd/","emoji":"🔍",
     "present":{"en":"I always find interesting books in the library.","cn":"我总在图书馆找到有趣的书。"},
     "past":{"en":"She found her lost keys under the sofa.","cn":"她在沙发下找到了丢失的钥匙。"},
     "perfect":{"en":"Researchers have found a new way to save energy.","cn":"研究人员发现了一种节能新方法。"}},
    {"id":"fly","base":"fly","past":"flew","pp":"flown","cn":"飞","ipa":"/flaɪ/","emoji":"✈️",
     "present":{"en":"Birds fly south when winter comes.","cn":"冬天来临时鸟儿飞向南方。"},
     "past":{"en":"We flew to Beijing for a school trip last summer.","cn":"去年夏天我们乘飞机去北京研学。"},
     "perfect":{"en":"Time has flown since we entered junior high.","cn":"自从上初中以来时间过得飞快。"}},
    {"id":"forget","base":"forget","past":"forgot","pp":"forgotten","cn":"忘记","ipa":"/fəˈɡɒt/","emoji":"🤔",
     "present":{"en":"Don't forget to hand in your homework on time.","cn":"别忘了按时交作业。"},
     "past":{"en":"He forgot his umbrella and got wet in the rain.","cn":"他忘了带伞，被雨淋湿了。"},
     "perfect":{"en":"I have never forgotten my teacher's kind advice.","cn":"我从未忘记老师善意的建议。"}},
    {"id":"get","base":"get","past":"got","pp":"got","cn":"得到；变得","ipa":"/ɡet/","emoji":"🎯",
     "present":{"en":"I get up at six thirty on school days.","cn":"上学日我六点半起床。"},
     "past":{"en":"She got a high mark in the maths test.","cn":"她在数学考试中得了高分。"},
     "perfect":{"en":"He has got used to getting up early.","cn":"他已经习惯早起了。"}},
    {"id":"give","base":"give","past":"gave","pp":"given","cn":"给","ipa":"/ɡɪv/","emoji":"🤝",
     "present":{"en":"Teachers give us useful advice every day.","cn":"老师每天给我们有用的建议。"},
     "past":{"en":"He gave his seat to an old lady on the bus.","cn":"他在公交车上给一位老奶奶让了座。"},
     "perfect":{"en":"The volunteer team has given help to many families.","cn":"志愿者团队已帮助了许多家庭。"}},
    {"id":"go","base":"go","past":"went","pp":"gone","cn":"去","ipa":"/ɡəʊ/","emoji":"🚶",
     "present":{"en":"We go to the sports field after class.","cn":"下课后我们去操场。"},
     "past":{"en":"They went to the museum on Children's Day.","cn":"儿童节他们去了博物馆。"},
     "perfect":{"en":"My cousin has gone abroad to study medicine.","cn":"我表哥已出国学医了。"}},
    {"id":"grow","base":"grow","past":"grew","pp":"grown","cn":"生长；种植","ipa":"/ɡrəʊ/","emoji":"🌱",
     "present":{"en":"Plants grow fast with enough sunlight and water.","cn":"阳光和水分充足时植物长得快。"},
     "past":{"en":"We grew tomatoes in the school garden last spring.","cn":"去年春天我们在学校菜园种了西红柿。"},
     "perfect":{"en":"The city has grown into a modern centre of trade.","cn":"这座城市已发展成现代贸易中心。"}},
    {"id":"hang","base":"hang","past":"hung","pp":"hung","cn":"悬挂","ipa":"/hæŋ/","emoji":"🖼️",
     "present":{"en":"We hang our coats on hooks in the classroom.","cn":"我们把外套挂在教室的钩子上。"},
     "past":{"en":"She hung colourful posters on the wall.","cn":"她在墙上挂了彩色海报。"},
     "perfect":{"en":"A new picture has hung in the art room since Monday.","cn":"从周一起美术室挂了一幅新画。"}},
    {"id":"have","base":"have","past":"had","pp":"had","cn":"有；吃","ipa":"/hæv/","emoji":"📚",
     "present":{"en":"I have English class three times a week.","cn":"我每周上三次英语课。"},
     "past":{"en":"We had a wonderful picnic in the park last Sunday.","cn":"上周日我们在公园野餐，非常开心。"},
     "perfect":{"en":"She has had this bike since she was ten.","cn":"她从十岁起就拥有这辆自行车。"}},
    {"id":"hear","base":"hear","past":"heard","pp":"heard","cn":"听见","ipa":"/hɪə/","emoji":"👂",
     "present":{"en":"I hear birds singing outside my window every morning.","cn":"每天早上我听到窗外鸟儿歌唱。"},
     "past":{"en":"We heard exciting news about the school festival.","cn":"我们听到了关于校园节的激动人心的消息。"},
     "perfect":{"en":"Have you ever heard of this famous scientist?","cn":"你听说过这位著名科学家吗？"}},
    {"id":"hit","base":"hit","past":"hit","pp":"hit","cn":"打；撞击","ipa":"/hɪt/","emoji":"⚾",
     "present":{"en":"The ball hits the wall when you throw it hard.","cn":"用力扔球时球会撞到墙上。"},
     "past":{"en":"The car hit a tree in the heavy fog.","cn":"浓雾中汽车撞上了一棵树。"},
     "perfect":{"en":"The typhoon has hit the coast and caused floods.","cn":"台风已袭击海岸并引发洪水。"}},
    {"id":"hurt","base":"hurt","past":"hurt","pp":"hurt","cn":"伤害；疼","ipa":"/hɜːt/","emoji":"🩹",
     "present":{"en":"Sharp words can hurt your friends' feelings.","cn":"尖刻的话会伤害朋友的感情。"},
     "past":{"en":"He hurt his knee when he played basketball.","cn":"他打篮球时膝盖受伤了。"},
     "perfect":{"en":"The accident has hurt several people seriously.","cn":"事故已致多人重伤。"}},
    {"id":"hold","base":"hold","past":"held","pp":"held","cn":"拿着；举行","ipa":"/həʊld/","emoji":"🤲",
     "present":{"en":"Please hold the door open for the person behind you.","cn":"请为身后的人扶着门。"},
     "past":{"en":"Our school held a charity sale last Friday.","cn":"上周五学校举办了义卖活动。"},
     "perfect":{"en":"Beijing has held many important international events.","cn":"北京已举办过许多重要国际活动。"}},
    {"id":"keep","base":"keep","past":"kept","pp":"kept","cn":"保持；饲养","ipa":"/kept/","emoji":"🔒",
     "present":{"en":"Keep quiet in the library so others can read.","cn":"图书馆请保持安静，方便他人阅读。"},
     "past":{"en":"She kept a diary to improve her writing.","cn":"她坚持写日记来提高写作。"},
     "perfect":{"en":"We have kept in touch since we left primary school.","cn":"自小学毕业以来我们一直保持着联系。"}},
    {"id":"know","base":"know","past":"knew","pp":"known","cn":"知道；认识","ipa":"/nəʊ/","emoji":"💡",
     "present":{"en":"I know many useful English phrases for daily talk.","cn":"我知道许多日常交流有用的英语短语。"},
     "past":{"en":"He knew the answer but was too shy to speak.","cn":"他知道答案但太害羞没开口。"},
     "perfect":{"en":"China has been known as a country of inventions.","cn":"中国一直以发明之国而闻名。"}},
    {"id":"lead","base":"lead","past":"led","pp":"led","cn":"带领；导致","ipa":"/liːd/","emoji":"🧭",
     "present":{"en":"A good monitor leads the class with confidence.","cn":"好班长能自信地带领全班。"},
     "past":{"en":"The guide led us through the ancient temple.","cn":"导游带领我们穿过古庙。"},
     "perfect":{"en":"Hard work has led him to many awards.","cn":"勤奋使他获得了许多奖项。"}},
    {"id":"leave","base":"leave","past":"left","pp":"left","cn":"离开；留下","ipa":"/liːv/","emoji":"🚪",
     "present":{"en":"Don't leave your bag on the floor in the classroom.","cn":"别把书包放在教室地上。"},
     "past":{"en":"They left the city and moved to the countryside.","cn":"他们离开城市搬到了乡下。"},
     "perfect":{"en":"He has left a deep impression on all his classmates.","cn":"他给所有同学留下了深刻印象。"}},
    {"id":"lend","base":"lend","past":"lent","pp":"lent","cn":"借出","ipa":"/lend/","emoji":"📖",
     "present":{"en":"Could you lend me your ruler for a moment?","cn":"能借我用一下你的尺子吗？"},
     "past":{"en":"She lent her notes to a classmate who was ill.","cn":"她把笔记借给了一位生病的同学。"},
     "perfect":{"en":"The library has lent out hundreds of books this month.","cn":"图书馆本月已借出数百本书。"}},
    {"id":"let","base":"let","past":"let","pp":"let","cn":"让","ipa":"/let/","emoji":"🚦",
     "present":{"en":"My parents let me join the school choir.","cn":"父母允许我加入学校合唱团。"},
     "past":{"en":"The teacher let us discuss the topic in groups.","cn":"老师让我们分组讨论这个话题。"},
     "perfect":{"en":"Don't let small mistakes stop you from trying again.","cn":"别让小小失误阻止你再次尝试。"}},
    {"id":"lie","base":"lie","past":"lay","pp":"lain","cn":"躺；位于","ipa":"/laɪ/","emoji":"🛏️",
     "present":{"en":"The small town lies between two green hills.","cn":"小镇坐落在两座青山之间。"},
     "past":{"en":"He lay on the grass and watched the clouds.","cn":"他躺在草地上看云。"},
     "perfect":{"en":"The problem has lain unsolved for a long time.","cn":"这个问题长期未能解决。"}},
    {"id":"light","base":"light","past":"lit","pp":"lit","cn":"点亮","ipa":"/laɪt/","emoji":"💡",
     "present":{"en":"We light candles on birthdays to make a wish.","cn":"生日时我们点蜡烛许愿。"},
     "past":{"en":"She lit the lamp and continued reading.","cn":"她点亮灯继续阅读。"},
     "perfect":{"en":"Her smile has lit up the whole classroom.","cn":"她的笑容照亮了整个教室。"}},
    {"id":"lose","base":"lose","past":"lost","pp":"lost","cn":"丢失；输掉","ipa":"/luːz/","emoji":"😢",
     "present":{"en":"Take care of your things or you may lose them.","cn":"看好你的东西，否则可能会丢。"},
     "past":{"en":"Our team lost the match but learned a lot.","cn":"我们队输了比赛但收获很多。"},
     "perfect":{"en":"He has lost his wallet twice this month.","cn":"这个月他已经丢了两次钱包。"}},
    {"id":"make","base":"make","past":"made","pp":"made","cn":"制作；使","ipa":"/meɪk/","emoji":"🔨",
     "present":{"en":"We make paper flowers in the craft lesson.","cn":"我们在手工课上做纸花。"},
     "past":{"en":"She made a birthday card for her best friend.","cn":"她给最好的朋友做了生日贺卡。"},
     "perfect":{"en":"Practice has made her pronunciation much clearer.","cn":"练习使她的发音清晰了许多。"}},
    {"id":"mean","base":"mean","past":"meant","pp":"meant","cn":"意思是；意味着","ipa":"/miːn/","emoji":"📖",
     "present":{"en":"What does this word mean in the sentence?","cn":"这个词在句中是什么意思？"},
     "past":{"en":"He meant to help, but his words sounded rude.","cn":"他本想帮忙，但话听起来很粗鲁。"},
     "perfect":{"en":"Hard work has meant success for many students.","cn":"对许多学生来说，勤奋意味着成功。"}},
    {"id":"meet","base":"meet","past":"met","pp":"met","cn":"遇见；开会","ipa":"/miːt/","emoji":"👥",
     "present":{"en":"I meet my classmates at the school gate every morning.","cn":"每天早上我在校门口遇见同学。"},
     "past":{"en":"We met a friendly guide at the museum entrance.","cn":"我们在博物馆入口遇见了一位热情的导游。"},
     "perfect":{"en":"I have met many interesting people through volunteering.","cn":"通过志愿服务我遇见了许多有趣的人。"}},
    {"id":"pay","base":"pay","past":"paid","pp":"paid","cn":"付款","ipa":"/peɪ/","emoji":"💳",
     "present":{"en":"Students pay attention when the teacher explains grammar.","cn":"老师讲语法时同学们认真听讲。"},
     "past":{"en":"He paid ten yuan for lunch in the canteen.","cn":"他在食堂付了十元午餐费。"},
     "perfect":{"en":"She has paid great effort to improve her English.","cn":"她为提高英语付出了巨大努力。"}},
    {"id":"put","base":"put","past":"put","pp":"put","cn":"放","ipa":"/pʊt/","emoji":"📦",
     "present":{"en":"Put your phone away during the lesson, please.","cn":"上课请把手机收起来。"},
     "past":{"en":"She put the books back on the shelf after reading.","cn":"读完后她把书放回书架。"},
     "perfect":{"en":"We have put forward a plan to protect the environment.","cn":"我们已提出一项环保计划。"}},
    {"id":"read","base":"read","past":"read","pp":"read","cn":"读","ipa":"/riːd/","emoji":"📕","ipa_note":"原形 /riːd/，过去式/分词 /red/",
     "present":{"en":"I read English stories for twenty minutes every night.","cn":"我每晚读二十分钟英语故事。"},
     "past":{"en":"He read the notice on the board carefully.","cn":"他仔细读了布告栏上的通知。"},
     "perfect":{"en":"She has read all the books on the reading list.","cn":"她已读完阅读清单上的所有书。"}},
    {"id":"ride","base":"ride","past":"rode","pp":"ridden","cn":"骑；乘坐","ipa":"/raɪd/","emoji":"🚲",
     "present":{"en":"I ride my bike to school when the weather is fine.","cn":"天气好时我骑自行车上学。"},
     "past":{"en":"We rode the roller coaster at the amusement park.","cn":"我们在游乐园坐了过山车。"},
     "perfect":{"en":"He has ridden a horse only once in his life.","cn":"他一生中只骑过一次马。"}},
    {"id":"ring","base":"ring","past":"rang","pp":"rung","cn":"响；打电话","ipa":"/rɪŋ/","emoji":"🔔",
     "present":{"en":"The school bell rings at eight every morning.","cn":"每天早上八点校铃响。"},
     "past":{"en":"The phone rang while I was doing homework.","cn":"我做作业时电话响了。"},
     "perfect":{"en":"Changes have rung in a new era of learning.","cn":"变革迎来了一个学习的新时代。"}},
    {"id":"rise","base":"rise","past":"rose","pp":"risen","cn":"上升；起床","ipa":"/raɪz/","emoji":"🌅",
     "present":{"en":"The sun rises in the east every morning.","cn":"太阳每天从东方升起。"},
     "past":{"en":"Smoke rose from the chimney on the cold morning.","cn":"寒冷的早晨烟囱里升起炊烟。"},
     "perfect":{"en":"Living costs have risen sharply in recent years.","cn":"近年来生活成本急剧上涨。"}},
    {"id":"run","base":"run","past":"ran","pp":"run","cn":"跑；经营","ipa":"/rʌn/","emoji":"🏃",
     "present":{"en":"I run on the track every afternoon after school.","cn":"每天放学后我在跑道上跑步。"},
     "past":{"en":"She ran to catch the last bus home.","cn":"她跑去赶末班公交车回家。"},
     "perfect":{"en":"The programme has run successfully for three years.","cn":"该项目已成功运行三年。"}},
    {"id":"say","base":"say","past":"said","pp":"said","cn":"说","ipa":"/seɪ/","emoji":"💬",
     "present":{"en":"Teachers say encouraging words to help us grow.","cn":"老师说鼓励的话帮助我们成长。"},
     "past":{"en":"He said sorry and returned the borrowed book.","cn":"他道了歉并归还了借的书。"},
     "perfect":{"en":"As the saying goes, practice makes perfect.","cn":"俗话说，熟能生巧。"}},
    {"id":"see","base":"see","past":"saw","pp":"seen","cn":"看见","ipa":"/siː/","emoji":"👁️",
     "present":{"en":"I see my neighbours walking their dogs every evening.","cn":"我每晚看见邻居遛狗。"},
     "past":{"en":"We saw a rainbow after the summer shower.","cn":"夏日阵雨后我们看见了彩虹。"},
     "perfect":{"en":"Have you ever seen such a beautiful sunset?","cn":"你见过这么美的日落吗？"}},
    {"id":"sell","base":"sell","past":"sold","pp":"sold","cn":"卖","ipa":"/səʊld/","emoji":"🏪",
     "present":{"en":"The shop sells stationery near our school gate.","cn":"校门口那家店卖文具。"},
     "past":{"en":"They sold handmade crafts at the school fair.","cn":"他们在校园义卖上卖了手工艺品。"},
     "perfect":{"en":"The book has sold millions of copies worldwide.","cn":"这本书在全球已售出数百万册。"}},
    {"id":"send","base":"send","past":"sent","pp":"sent","cn":"发送；派遣","ipa":"/sent/","emoji":"✉️",
     "present":{"en":"Please send me the homework file by email tonight.","cn":"请今晚把作业文件用邮件发给我。"},
     "past":{"en":"The school sent a notice about the sports meeting.","cn":"学校发了关于运动会的通知。"},
     "perfect":{"en":"China has sent aid to countries in need.","cn":"中国已向有需要的国家提供了援助。"}},
    {"id":"set","base":"set","past":"set","pp":"set","cn":"放置；设定","ipa":"/set/","emoji":"⏰",
     "present":{"en":"I set my alarm clock for six every school day.","cn":"上学日我把闹钟定在六点。"},
     "past":{"en":"She set a new record in the long jump.","cn":"她在跳远项目中创造了新纪录。"},
     "perfect":{"en":"We have set a clear goal for this semester.","cn":"我们为本学期设定了明确目标。"}},
    {"id":"shoot","base":"shoot","past":"shot","pp":"shot","cn":"射击；拍摄","ipa":"/ʃuːt/","emoji":"📷",
     "present":{"en":"The photographer shoots pictures of school events.","cn":"摄影师拍摄校园活动照片。"},
     "past":{"en":"He shot the winning goal in the final minute.","cn":"他在最后一分钟射进了制胜一球。"},
     "perfect":{"en":"The film crew has shot scenes in many cities.","cn":"摄制组已在多座城市取景拍摄。"}},
    {"id":"show","base":"show","past":"showed","pp":"shown","cn":"展示；给…看","ipa":"/ʃəʊ/","emoji":"🎬",
     "present":{"en":"Good students show respect to teachers and classmates.","cn":"好学生尊敬老师和同学。"},
     "past":{"en":"She showed us how to use the science equipment.","cn":"她向我们演示了如何使用实验器材。"},
     "perfect":{"en":"The data has shown that reading improves writing skills.","cn":"数据表明阅读能提高写作能力。"}},
    {"id":"sing","base":"sing","past":"sang","pp":"sung","cn":"唱","ipa":"/sɪŋ/","emoji":"🎤",
     "present":{"en":"We sing the school song at every assembly.","cn":"每次集会我们都唱校歌。"},
     "past":{"en":"She sang a folk song at the art festival.","cn":"她在艺术节上唱了一首民歌。"},
     "perfect":{"en":"He has sung on stage many times this year.","cn":"今年他已在舞台上演唱多次。"}},
    {"id":"sit","base":"sit","past":"sat","pp":"sat","cn":"坐","ipa":"/sɪt/","emoji":"🪑",
     "present":{"en":"Please sit straight and listen carefully in class.","cn":"上课请坐直认真听。"},
     "past":{"en":"We sat under a big tree and shared our lunch.","cn":"我们坐在大树下分享午餐。"},
     "perfect":{"en":"She has sat the entrance exam twice.","cn":"她已参加过两次升学考试。"}},
    {"id":"sleep","base":"sleep","past":"slept","pp":"slept","cn":"睡觉","ipa":"/sliːp/","emoji":"😴",
     "present":{"en":"Children need enough sleep to grow healthily.","cn":"孩子需要充足睡眠才能健康成长。"},
     "past":{"en":"He slept only five hours before the big exam.","cn":"大考前他只睡了五小时。"},
     "perfect":{"en":"I have slept badly because of the noisy construction.","cn":"因施工噪音我睡得不好。"}},
    {"id":"speak","base":"speak","past":"spoke","pp":"spoken","cn":"说；讲","ipa":"/spiːk/","emoji":"🗣️",
     "present":{"en":"She speaks English confidently in front of the class.","cn":"她在全班面前自信地说英语。"},
     "past":{"en":"He spoke about environmental protection at the meeting.","cn":"他在会上讲了环境保护。"},
     "perfect":{"en":"English is spoken in many countries around the world.","cn":"世界上许多国家都说英语。"}},
    {"id":"spend","base":"spend","past":"spent","pp":"spent","cn":"花费；度过","ipa":"/spend/","emoji":"⏳",
     "present":{"en":"I spend an hour practising listening every day.","cn":"我每天花一小时练听力。"},
     "past":{"en":"We spent a happy weekend at my grandparents' farm.","cn":"我们在祖父母农场度过了愉快的周末。"},
     "perfect":{"en":"She has spent years learning to play the piano.","cn":"她学钢琴已学了好几年。"}},
    {"id":"stand","base":"stand","past":"stood","pp":"stood","cn":"站立；忍受","ipa":"/stænd/","emoji":"🧍‍♂️",
     "present":{"en":"Students stand up when the teacher enters the room.","cn":"老师进教室时学生起立。"},
     "past":{"en":"He stood first in the long-distance race.","cn":"他在长跑比赛中获得第一名。"},
     "perfect":{"en":"The tower has stood there for over six hundred years.","cn":"这座塔已矗立六百多年。"}},
    {"id":"steal","base":"steal","past":"stole","pp":"stolen","cn":"偷","ipa":"/stiːl/","emoji":"🚫",
     "present":{"en":"Never steal others' ideas in a group project.","cn":"小组作业中切勿剽窃他人想法。"},
     "past":{"en":"Someone stole a bike from the school parking area.","cn":"有人从学校停车区偷了一辆自行车。"},
     "perfect":{"en":"The thief has stolen several phones this month.","cn":"这个月小偷已偷了好几部手机。"}},
    {"id":"strike","base":"strike","past":"struck","pp":"struck","cn":"打击；撞击","ipa":"/straɪk/","emoji":"⚡",
     "present":{"en":"Lightning can strike tall buildings during storms.","cn":"暴风雨中闪电可能击中高楼。"},
     "past":{"en":"The clock struck twelve at midnight.","cn":"午夜时钟敲了十二下。"},
     "perfect":{"en":"The earthquake has struck the region twice this year.","cn":"今年地震已两次袭击该地区。"}},
    {"id":"swim","base":"swim","past":"swam","pp":"swum","cn":"游泳","ipa":"/swɪm/","emoji":"🏊",
     "present":{"en":"I swim in the pool twice a week in summer.","cn":"夏天我每周去泳池游两次。"},
     "past":{"en":"She swam across the river during the training camp.","cn":"集训时她游过了那条河。"},
     "perfect":{"en":"He has swum in national competitions three times.","cn":"他已三次参加全国游泳比赛。"}},
    {"id":"take","base":"take","past":"took","pp":"taken","cn":"拿；花费","ipa":"/teɪk/","emoji":"🤏",
     "present":{"en":"It takes me twenty minutes to walk to school.","cn":"我步行上学要花二十分钟。"},
     "past":{"en":"She took careful notes during the science lesson.","cn":"科学课上她做了详细笔记。"},
     "perfect":{"en":"Great changes have taken place in my hometown.","cn":"我的家乡已发生了巨大变化。"}},
    {"id":"teach","base":"teach","past":"taught","pp":"taught","cn":"教","ipa":"/tiːtʃ/","emoji":"👩‍🏫",
     "present":{"en":"Our English teacher teaches us with patience and humour.","cn":"英语老师耐心幽默地教我们。"},
     "past":{"en":"He taught his little sister how to ride a bike.","cn":"他教妹妹骑自行车。"},
     "perfect":{"en":"Experience has taught me to plan ahead.","cn":"经历教会了我提前规划。"}},
    {"id":"tell","base":"tell","past":"told","pp":"told","cn":"告诉","ipa":"/tel/","emoji":"📢",
     "present":{"en":"Please tell the truth even when it is hard.","cn":"即使困难也请说实话。"},
     "past":{"en":"Grandma told us an interesting story before bed.","cn":"睡前奶奶给我们讲了一个有趣的故事。"},
     "perfect":{"en":"She has told me about her dream of becoming a doctor.","cn":"她告诉过我她想当医生的梦想。"}},
    {"id":"think","base":"think","past":"thought","pp":"thought","cn":"想；认为","ipa":"/θɪŋk/","emoji":"🧠",
     "present":{"en":"I think teamwork is more important than winning alone.","cn":"我认为团队合作比独自获胜更重要。"},
     "past":{"en":"He thought carefully before answering the question.","cn":"他认真思考后才回答问题。"},
     "perfect":{"en":"Scientists have thought of new ways to save water.","cn":"科学家想出了节水新方法。"}},
    {"id":"throw","base":"throw","past":"threw","pp":"thrown","cn":"扔","ipa":"/θruː/","emoji":"🎯",
     "present":{"en":"Don't throw rubbish on the ground in the park.","cn":"公园里别往地上扔垃圾。"},
     "past":{"en":"He threw the ball to his teammate on the field.","cn":"他把球传给了场上的队友。"},
     "perfect":{"en":"Too much plastic has been thrown into the ocean.","cn":"太多塑料已被扔进海洋。"}},
    {"id":"understand","base":"understand","past":"understood","pp":"understood","cn":"理解","ipa":"/ˌʌndəˈstænd/","emoji":"🤓",
     "present":{"en":"I understand the grammar rule after the teacher's explanation.","cn":"经老师讲解我理解了这条语法。"},
     "past":{"en":"She understood the poem better after reading it aloud.","cn":"朗读后她更理解这首诗了。"},
     "perfect":{"en":"We have understood the importance of protecting wildlife.","cn":"我们已认识到保护野生动物的重要性。"}},
    {"id":"wake","base":"wake","past":"woke","pp":"woken","cn":"醒来","ipa":"/weɪk/","emoji":"⏰",
     "present":{"en":"I wake up early to review English words.","cn":"我早起复习英语单词。"},
     "past":{"en":"The loud thunder woke me up in the middle of the night.","cn":"半夜响雷把我惊醒了。"},
     "perfect":{"en":"He has woken up to the value of daily exercise.","cn":"他已认识到日常锻炼的价值。"}},
    {"id":"wear","base":"wear","past":"wore","pp":"worn","cn":"穿；戴","ipa":"/weə/","emoji":"👕",
     "present":{"en":"Students wear uniforms to school on weekdays.","cn":"工作日学生穿校服上学。"},
     "past":{"en":"She wore a red dress at the school concert.","cn":"她在学校音乐会上穿了红裙子。"},
     "perfect":{"en":"He has worn the same lucky watch for years.","cn":"他多年来一直戴着那块幸运手表。"}},
    {"id":"win","base":"win","past":"won","pp":"won","cn":"赢","ipa":"/wɪn/","emoji":"🏆",
     "present":{"en":"Our class always tries hard to win the sports cup.","cn":"我们班总是努力争取赢得运动杯。"},
     "past":{"en":"She won first prize in the English speech contest.","cn":"她在英语演讲比赛中获一等奖。"},
     "perfect":{"en":"The team has won five matches in a row this season.","cn":"本赛季该队已连续赢五场比赛。"}},
    {"id":"write","base":"write","past":"wrote","pp":"written","cn":"写","ipa":"/raɪt/","emoji":"✏️",
     "present":{"en":"I write a short diary in English every weekend.","cn":"我每周末用英语写简短日记。"},
     "past":{"en":"He wrote a thank-you letter to his teacher.","cn":"他给老师写了一封感谢信。"},
     "perfect":{"en":"She has written three articles for the school newspaper.","cn":"她已为校报写了三篇文章。"}},
]

MEDIA_BASE = "https://s-class-1403296481.cos.ap-chengdu.myqcloud.com/s-class/irregular_verbs/images/"

for v in VERBS:
    vid = v["id"]
    v["image"] = MEDIA_BASE + vid + ".png"
    v["images"] = {
        "verb": MEDIA_BASE + vid + ".png",
        "present": MEDIA_BASE + vid + "_present.png",
        "past": MEDIA_BASE + vid + "_past.png",
        "perfect": MEDIA_BASE + vid + "_perfect.png",
    }
    v["examples"] = {
        "present": {**v.pop("present"), "tense": "一般现在时", "level": "初一"},
        "past": {**v.pop("past"), "tense": "一般过去时", "level": "初一"},
        "perfect": {**v.pop("perfect"), "tense": "现在完成时", "level": "初三中考"},
    }
    v.pop("emoji", None)

output = {
    "version": 1,
    "mediaBase": MEDIA_BASE,
    "verbs": VERBS,
}

js = "/**\n * 初中不规则动词 · 80 词完整数据\n * 含原形/过去式/过去分词 + 三时态例句\n */\n"
js += "window.IRREGULAR_VERBS_DATA = " + json.dumps(output, ensure_ascii=False, indent=2) + ";\n"

with open("/workspace/irregular_verbs/verbs-data.js", "w", encoding="utf-8") as f:
    f.write(js)

print(f"Generated {len(VERBS)} verbs -> verbs-data.js")
