# -*- coding: utf-8 -*-
"""人教版英语九年级上册（2024/2026 秋新版）单元词汇。

词条依据教材 Vocabulary in Each Unit / A–Z，并对照较清晰的公开词表校对。
人名、纯专名角色名不收入课件；地名、文化专名、航天器名保留。
"""

UNIT_TITLES = {
    1: ("The Changing World", "变化的世界"),
    2: ("Inspiring People", "鼓舞人心的人"),
    3: ("Smart Learning", "聪明地学习"),
    4: ("Our Memory", "我们的记忆"),
    5: ("Power of Ideas", "思想的力量"),
    6: ("Beyond Earth", "超越地球"),
    7: ("Feel the Rhythm", "感受节奏"),
    8: ("More than a Game", "不止是一场比赛"),
}

# (word, ipa, usage, meaning_cn)
UNITS = {
    1: [
        ("bring about", "/brɪŋ əˈbaʊt/", "phr.", "带来；引起"),
        ("rough", "/rʌf/", "adj.", "崎岖的"),
        ("be covered with", "/bi ˈkʌvəd wɪð/", "phr.", "被……覆盖"),
        ("sandstorm", "/ˈsændstɔːm/", "n.", "沙尘暴"),
        ("farmland", "/ˈfɑːmlænd/", "n.", "耕地"),
        ("shortage", "/ˈʃɔːtɪdʒ/", "n.", "短缺"),
        ("lack", "/læk/", "n. / v.", "缺乏"),
        ("bush", "/bʊʃ/", "n.", "灌木"),
        ("root", "/ruːt/", "n.", "根"),
        ("soil", "/sɔɪl/", "n.", "土壤"),
        ("sandy", "/ˈsændi/", "adj.", "铺满沙子的；含沙的"),
        ("government", "/ˈɡʌvənmənt/", "n.", "政府"),
        ("support", "/səˈpɔːt/", "n. & v.", "支持"),
        ("corn", "/kɔːn/", "n.", "玉米；谷物"),
        ("high-tech", "/ˌhaɪ ˈtek/", "adj.", "高科技的"),
        ("greenhouse", "/ˈɡriːnhaʊs/", "n.", "温室"),
        ("highway", "/ˈhaɪweɪ/", "n.", "公路"),
        ("railway", "/ˈreɪlweɪ/", "n.", "铁路"),
        ("attraction", "/əˈtrækʃn/", "n.", "向往的地方；吸引力"),
        ("product", "/ˈprɒdʌkt/", "n.", "产品"),
        ("greatly", "/ˈɡreɪtli/", "adv.", "大大地；非常"),
        ("socialist", "/ˈsəʊʃəlɪst/", "adj. / n.", "社会主义的；社会主义者"),
        ("e-payment", "/ˈiː peɪmənt/", "n.", "电子支付"),
        ("housing", "/ˈhaʊzɪŋ/", "n.", "住房；住宅"),
        ("digital", "/ˈdɪdʒɪtl/", "adj.", "电子的"),
        ("audio", "/ˈɔːdiəʊ/", "adj. / n.", "音频的；音频"),
        ("dirt", "/dɜːt/", "n.", "泥土；尘土"),
        ("track", "/træk/", "n.", "小路；轨道"),
        ("wide", "/waɪd/", "adj.", "宽的；宽阔的"),
        ("link", "/lɪŋk/", "n. / v.", "交通路线；联系；连接"),
        ("port", "/pɔːt/", "n.", "港口"),
        ("capital", "/ˈkæpɪtl/", "n.", "首都"),
        ("Kenyan", "/ˈkenjən/", "n. / adj.", "肯尼亚人；肯尼亚的"),
        ("benefit", "/ˈbenɪfɪt/", "v. / n.", "得益于；使受益；优势；益处"),
        ("be happy with", "/bi ˈhæpi wɪð/", "phr.", "对……感到满意"),
        ("convenient", "/kənˈviːniənt/", "adj.", "方便的"),
        ("business", "/ˈbɪznəs/", "n.", "生意；商业"),
        ("ease", "/iːz/", "n.", "容易；自在"),
        ("with ease", "/wɪð iːz/", "phr.", "轻而易举地"),
        ("lorry", "/ˈlɒri/", "n.", "卡车"),
        ("manager", "/ˈmænɪdʒə(r)/", "n.", "经理"),
        ("conclusion", "/kənˈkluːʒn/", "n.", "总结；结论"),
        ("narrow", "/ˈnærəʊ/", "adj.", "狭窄的"),
        ("villager", "/ˈvɪlɪdʒə(r)/", "n.", "村民"),
        ("the Olympics", "/ði əˈlɪmpɪks/", "n.", "奥林匹克运动会"),
        ("lead", "/liːd/", "v. (led, led) / n.", "带领；过（某种生活）；领先地位"),
        ("man-made", "/ˌmæn ˈmeɪd/", "adj.", "人造的；非天然的"),
        ("miracle", "/ˈmɪrəkl/", "n.", "奇迹"),
        ("junior", "/ˈdʒuːniə(r)/", "adj.", "低年级的；初级的"),
        ("flat", "/flæt/", "n.", "公寓"),
        ("discussion", "/dɪˈskʌʃn/", "n.", "讨论"),
        ("aspect", "/ˈæspekt/", "n.", "方面"),
        ("Mombasa", "/mɒmˈbæsə/", "n.", "蒙巴萨（肯尼亚城市）"),
    ],
    2: [
        ("inspiring", "/ɪnˈspaɪərɪŋ/", "adj.", "鼓舞人心的；激励的"),
        ("admire", "/ədˈmaɪə(r)/", "v.", "钦佩；赞赏"),
        ("historian", "/hɪˈstɔːriən/", "n.", "历史学家"),
        ("researcher", "/rɪˈsɜːtʃə(r)/", "n.", "研究人员"),
        ("chemist", "/ˈkemɪst/", "n.", "化学家"),
        ("physicist", "/ˈfɪzɪsɪst/", "n.", "物理学家"),
        ("hunger", "/ˈhʌŋɡə(r)/", "n.", "饥饿"),
        ("chemistry", "/ˈkemɪstri/", "n.", "化学"),
        ("drop out", "/drɒp aʊt/", "phr.", "辍学；不再参加"),
        ("calendar", "/ˈkælɪndə(r)/", "n.", "日历"),
        ("discovery", "/dɪˈskʌvəri/", "n.", "发现"),
        ("century", "/ˈsentʃəri/", "n.", "世纪"),
        ("wounded", "/ˈwuːndɪd/", "adj.", "受伤的；负伤的"),
        ("soldier", "/ˈsəʊldʒə(r)/", "n.", "士兵"),
        ("British", "/ˈbrɪtɪʃ/", "adj. / n.", "英国的；英国人"),
        ("airway", "/ˈeəweɪ/", "n.", "（飞机的）航线；航路"),
        ("nation", "/ˈneɪʃn/", "n.", "国家；民族"),
        ("spread", "/spred/", "n. / v. (spread, spread)", "传播；散布"),
        ("disease", "/dɪˈziːz/", "n.", "疾病"),
        ("pioneer", "/ˌpaɪəˈnɪə(r)/", "n.", "先驱；先锋"),
        ("admirable", "/ˈædmərəbl/", "adj.", "令人钦佩的"),
        ("pyramid", "/ˈpɪrəmɪd/", "n.", "金字塔"),
        ("balance", "/ˈbæləns/", "n. / v.", "平衡；保持平衡"),
        ("courage", "/ˈkʌrɪdʒ/", "n.", "勇气；勇敢"),
        ("wisdom", "/ˈwɪzdəm/", "n.", "智慧；学问"),
        ("look up to", "/lʊk ʌp tuː/", "phr.", "钦佩；仰慕"),
        ("inspiration", "/ˌɪnspəˈreɪʃn/", "n.", "鼓舞人心的人（或事物）"),
        ("brave", "/breɪv/", "adj. / v.", "勇敢的；无畏的；勇敢面对"),
        ("necessary", "/ˈnesəsəri/", "adj.", "必要的；必需的"),
        ("seed", "/siːd/", "n.", "种子"),
        ("childhood", "/ˈtʃaɪldhʊd/", "n.", "童年"),
        ("come true", "/kʌm truː/", "phr.", "实现；成为现实"),
        ("dynasty", "/ˈdɪnəsti/", "n.", "朝代；王朝"),
        ("western", "/ˈwestən/", "adj.", "西方的；西部的"),
        ("scientific", "/ˌsaɪənˈtɪfɪk/", "adj.", "科学（上）的"),
        ("biologist", "/baɪˈɒlədʒɪst/", "n.", "生物学家"),
        ("whole", "/həʊl/", "adj.", "所有的；完全的"),
        ("bank", "/bæŋk/", "n.", "银行"),
        ("forever", "/fərˈevə(r)/", "adv.", "永远"),
        ("radio", "/ˈreɪdiəʊ/", "n.", "无线电；收音机"),
        ("leave behind", "/liːv bɪˈhaɪnd/", "phr.", "留下；遗留"),
        ("collection", "/kəˈlekʃn/", "n.", "收集物；收藏品"),
        ("live on", "/lɪv ɒn/", "phr.", "继续存在；继续活着"),
        ("exploration", "/ˌekspləˈreɪʃn/", "n.", "探索"),
        ("universe", "/ˈjuːnɪvɜːs/", "n.", "宇宙"),
        ("socialism", "/ˈsəʊʃəlɪzəm/", "n.", "社会主义"),
        ("hole", "/həʊl/", "n.", "洞；孔"),
        ("daughter", "/ˈdɔːtə(r)/", "n.", "女儿"),
        ("herself", "/hɜːˈself/", "pron.", "她自己；她本人"),
        ("flight", "/flaɪt/", "n.", "飞行；航班"),
        ("woodwork", "/ˈwʊdwɜːk/", "n.", "木工手艺"),
        ("inventor", "/ɪnˈventə(r)/", "n.", "发明家"),
        ("above all", "/əˈbʌv ɔːl/", "phr.", "最重要的是；尤其是"),
        ("thinker", "/ˈθɪŋkə(r)/", "n.", "思想家"),
        ("period", "/ˈpɪəriəd/", "n.", "时期；一段时间"),
        ("kingdom", "/ˈkɪŋdəm/", "n.", "王国"),
        ("kindness", "/ˈkaɪndnəs/", "n.", "善良"),
        ("whether", "/ˈweðə(r)/", "conj.", "是否"),
        ("mankind", "/mænˈkaɪnd/", "n.", "人类"),
        ("Atlantic Ocean", "/ətˈlæntɪk ˈəʊʃn/", "n.", "大西洋"),
        ("BCE", "/ˌbiː siː ˈiː/", "n.", "公元前"),
        ("the Warring States Period", "", "n.", "战国时期"),
        ("Nobel Prize", "/nəʊˈbel praɪz/", "n.", "诺贝尔奖"),
        ("the Silk Road", "", "n.", "丝绸之路"),
    ],
    3: [
        ("learner", "/ˈlɜːnə(r)/", "n.", "学习者"),
        ("flashcard", "/ˈflæʃkɑːd/", "n.", "（用于学习的）卡片；抽认卡"),
        ("project", "/ˈprɒdʒekt/", "n.", "计划；项目"),
        ("website", "/ˈwebsaɪt/", "n.", "网站"),
        ("hands-on", "/ˌhændz ˈɒn/", "adj.", "动手的；实际操作的"),
        ("experiment", "/ɪkˈsperɪmənt/", "n.", "实验；试验"),
        ("look up", "/lʊk ʌp/", "phr.", "查阅；检查"),
        ("dictionary", "/ˈdɪkʃənri/", "n.", "词典；字典"),
        ("aloud", "/əˈlaʊd/", "adv.", "出声地；大声地"),
        ("dialogue", "/ˈdaɪəlɒɡ/", "n.", "对话；对白"),
        ("suit", "/suːt/", "v. / n.", "适合；有利于；套装"),
        ("general", "/ˈdʒenrəl/", "adj.", "总的；大体的"),
        ("in general", "/ɪn ˈdʒenrəl/", "phr.", "总的来说；通常"),
        ("speed", "/spiːd/", "n. / v. (sped/speeded)", "速度；加速；促进"),
        ("grammar", "/ˈɡræmə(r)/", "n.", "语法"),
        ("podcast", "/ˈpɒdkɑːst/", "n.", "播客"),
        ("zero", "/ˈzɪərəʊ/", "num.", "零；最低程度"),
        ("come across", "/kʌm əˈkrɒs/", "phr.", "（偶然）遇见；发现"),
        ("step by step", "/ˌstep baɪ ˈstep/", "phr.", "逐步地；循序渐进地"),
        ("build up", "/bɪld ʌp/", "phr.", "增加；加强；创建"),
        ("actively", "/ˈæktɪvli/", "adv.", "积极地"),
        ("enjoyable", "/ɪnˈdʒɔɪəbl/", "adj.", "有乐趣的；使人快乐的"),
        ("strategy", "/ˈstrætədʒi/", "n.", "策略"),
        ("put off", "/pʊt ɒf/", "phr.", "推迟；拖延"),
        ("correct", "/kəˈrekt/", "adj. / v.", "正确的；恰当的；纠正"),
        ("suggest", "/səˈdʒest/", "v.", "建议；提议"),
        ("method", "/ˈmeθəd/", "n.", "方法"),
        ("summarize", "/ˈsʌməraɪz/", "v.", "总结；概括"),
        ("growth", "/ɡrəʊθ/", "n.", "成长；增加"),
        ("mindset", "/ˈmaɪndset/", "n.", "观念模式"),
        ("material", "/məˈtɪəriəl/", "n.", "材料"),
        ("in part", "/ɪn pɑːt/", "phr.", "在某种程度上；部分地"),
        ("guidance", "/ˈɡaɪdns/", "n.", "指导"),
        ("feedback", "/ˈfiːdbæk/", "n.", "反馈的意见"),
        ("addition", "/əˈdɪʃn/", "n.", "添加；加法"),
        ("in addition", "/ɪn əˈdɪʃn/", "phr.", "另外；此外"),
        ("resource", "/rɪˈsɔːs/", "n.", "资源；资料"),
        ("textbook", "/ˈtekstbʊk/", "n.", "教科书；课本"),
        ("advantage", "/ədˈvɑːntɪdʒ/", "n.", "优势；优点"),
        ("take advantage of", "/teɪk ədˈvɑːntɪdʒ əv/", "phr.", "利用"),
        ("efficiently", "/ɪˈfɪʃntli/", "adv.", "效率高地"),
        ("valley", "/ˈvæli/", "n.", "山谷；溪谷"),
        ("pronunciation", "/prəˌnʌnsiˈeɪʃn/", "n.", "发音；读音"),
        ("click", "/klɪk/", "v.", "点击；（使）发出咔哒声"),
        ("magazine", "/ˌmæɡəˈziːn/", "n.", "杂志；期刊"),
        ("open up", "/ˈəʊpən ʌp/", "phr.", "打开；开放"),
        ("shelf", "/ʃelf/", "n. (pl. shelves)", "（墙壁、书橱等的）架子；搁板"),
        ("schoolwork", "/ˈskuːlwɜːk/", "n.", "学校作业"),
        ("print", "/prɪnt/", "n. / v.", "印刷品；打印；印刷"),
        ("newspaper", "/ˈnjuːzpeɪpə(r)/", "n.", "报纸"),
        ("e-book", "/ˈiː bʊk/", "n.", "电子书"),
        ("recent", "/ˈriːsnt/", "adj.", "最近的；最新的"),
        ("HSK", "/ˌeɪtʃ es ˈkeɪ/", "n.", "汉语水平考试"),
    ],
    4: [
        ("position", "/pəˈzɪʃn/", "n. / v.", "位置；地方；安置；使处于"),
        ("sadness", "/ˈsædnəs/", "n.", "悲伤"),
        ("run out", "/rʌn aʊt/", "phr.", "用完；耗尽"),
        ("react", "/riˈækt/", "v.", "作出反应；回应"),
        ("mix up", "/mɪks ʌp/", "phr.", "混淆；弄乱"),
        ("put sth to good use", "", "phr.", "有效使用（或利用）某物"),
        ("chain", "/tʃeɪn/", "n.", "链条"),
        ("stable", "/ˈsteɪbl/", "adj.", "稳定的；稳固的"),
        ("lecture", "/ˈlektʃə(r)/", "n.", "讲座；讲课"),
        ("retell", "/ˌriːˈtel/", "v.", "复述"),
        ("memorize", "/ˈmeməraɪz/", "v.", "记住；记忆"),
        ("tick", "/tɪk/", "v. / n.", "给……打钩；对号"),
        ("grandson", "/ˈɡrænsʌn/", "n.", "孙子；外孙"),
        ("go through", "/ɡəʊ θruː/", "phr.", "经历；仔细察看"),
        ("happen to", "/ˈhæpən tuː/", "phr.", "碰巧；使遭遇"),
        ("keep in mind", "/kiːp ɪn maɪnd/", "phr.", "记在心中；记住"),
        ("case", "/keɪs/", "n.", "情况；事实"),
        ("in sb's case", "", "phr.", "就某人的情况而言"),
        ("opera", "/ˈɒprə/", "n.", "歌剧；歌剧团"),
        ("ticket", "/ˈtɪkɪt/", "n.", "入场券；票"),
        ("wallet", "/ˈwɒlɪt/", "n.", "钱包"),
        ("picnic", "/ˈpɪknɪk/", "n. / v.", "野餐"),
        ("pardon", "/ˈpɑːdn/", "v. / interj.", "原谅；请再说一遍；抱歉"),
        ("airport", "/ˈeəpɔːt/", "n.", "机场"),
        ("gunshot", "/ˈɡʌnʃɒt/", "n.", "枪声；（射出的）炮弹"),
        ("grown-up", "/ˌɡrəʊn ˈʌp/", "adj. / n.", "成年的；成年人"),
        ("recall", "/rɪˈkɔːl/", "v.", "回忆起；回想起"),
        ("grapevine", "/ˈɡreɪpvaɪn/", "n.", "葡萄藤；葡萄树"),
        ("boost", "/buːst/", "v. / n.", "促进；使增长；帮助；增长"),
        ("to start with", "", "phr.", "首先"),
        ("short-term", "/ˌʃɔːt ˈtɜːm/", "adj.", "短期的"),
        ("long-term", "/ˌlɒŋ ˈtɜːm/", "adj.", "长期的"),
        ("technique", "/tekˈniːk/", "n.", "技巧"),
        ("passage", "/ˈpæsɪdʒ/", "n.", "段落；走廊"),
        ("likely", "/ˈlaɪkli/", "adj. / adv.", "可能的；很可能"),
        ("wear out", "/weə aʊt/", "phr.", "使疲乏；磨损"),
        ("discuss", "/dɪˈskʌs/", "v.", "讨论；谈论；商量"),
        ("image", "/ˈɪmɪdʒ/", "n.", "图像；形象"),
        ("graph", "/ɡrɑːf/", "n.", "图；图表"),
        ("view", "/vjuː/", "v. / n.", "看；观看；观点；视野"),
        ("effective", "/ɪˈfektɪv/", "adj.", "有效的"),
        ("engine", "/ˈendʒɪn/", "n.", "发动机"),
        ("fuel", "/ˈfjuːəl/", "n.", "燃料"),
        ("address", "/əˈdres/", "n.", "地址"),
        ("password", "/ˈpɑːswɜːd/", "n.", "密码；口令"),
        ("account", "/əˈkaʊnt/", "n.", "账户；账目"),
        ("increase", "/ˈɪŋkriːs/", "n. / v.", "增长；增加"),
        ("wild", "/waɪld/", "adj.", "野生的；自然生长的"),
        ("blood", "/blʌd/", "n.", "血"),
        ("wound", "/wuːnd/", "n. / v.", "伤口；创伤；使受伤"),
        ("mall", "/mɔːl/", "n.", "购物商场"),
        ("notebook", "/ˈnəʊtbʊk/", "n.", "笔记本；笔记本电脑"),
        ("squirrel", "/ˈskwɪrəl/", "n.", "松鼠"),
        ("nut", "/nʌt/", "n.", "坚果"),
        ("dolphin", "/ˈdɒlfɪn/", "n.", "海豚"),
        ("recognize", "/ˈrekəɡnaɪz/", "v.", "辨认出；认可"),
        ("outline", "/ˈaʊtlaɪn/", "n. / v.", "纲要；概述"),
        ("fully", "/ˈfʊli/", "adv.", "完全地"),
        ("divide", "/dɪˈvaɪd/", "v.", "（把……）分成"),
        ("divide into", "/dɪˈvaɪd ˈɪntə/", "phr.", "把某物分为"),
        ("one-size-fits-all", "/ˌwʌn saɪz fɪts ˈɔːl/", "adj.", "通用的"),
    ],
    5: [
        ("invention", "/ɪnˈvenʃn/", "n.", "发明；创造"),
        ("camera", "/ˈkæmrə/", "n.", "照相机；（电影）摄影机"),
        ("laptop", "/ˈlæptɒp/", "n.", "笔记本电脑"),
        ("high-speed train", "", "n.", "高速列车"),
        ("super", "/ˈsuːpə(r)/", "adj.", "超级的；顶好的"),
        ("sunglasses", "/ˈsʌŋɡlɑːsɪz/", "n.", "墨镜"),
        ("mini-", "/ˈmɪni/", "prefix", "微型的；极小的"),
        ("itself", "/ɪtˈself/", "pron.", "它自己"),
        ("button", "/ˈbʌtn/", "n.", "按钮；扣子"),
        ("hundreds of", "/ˈhʌndrədz əv/", "phr.", "许多；大量"),
        ("produce", "/prəˈdjuːs/", "v.", "生产；繁育"),
        ("file", "/faɪl/", "n.", "（计算机的）文件；文件夹"),
        ("plastic", "/ˈplæstɪk/", "n. & adj.", "塑料（的）"),
        ("printer", "/ˈprɪntə(r)/", "n.", "打印机；印刷公司"),
        ("invent", "/ɪnˈvent/", "v.", "发明；编造"),
        ("all over the world", "", "phr.", "全世界"),
        ("suppose", "/səˈpəʊz/", "v.", "认为；推断"),
        ("be supposed to", "/bi səˈpəʊzd tuː/", "phr.", "应当做（某事）或是（某物）"),
        ("wheel", "/wiːl/", "n.", "车轮；轮子"),
        ("frozen", "/ˈfrəʊzn/", "adj.", "冻硬的；冰封的"),
        ("complete", "/kəmˈpliːt/", "v. / adj.", "完成；结束；完全的；彻底的"),
        ("layer", "/ˈleɪə(r)/", "n.", "层；表层"),
        ("melt", "/melt/", "v.", "（使）融化；逐渐消失"),
        ("pipe", "/paɪp/", "n.", "管道；管子；烟斗"),
        ("tunnel", "/ˈtʌnl/", "n.", "隧道；地下通道"),
        ("tourism", "/ˈtʊərɪzəm/", "n.", "旅游业"),
        ("gain", "/ɡeɪn/", "v.", "获得；取得"),
        ("reality", "/riˈæləti/", "n.", "现实；事实"),
        ("papermaking", "/ˈpeɪpəˌmeɪkɪŋ/", "n.", "造纸工艺；造纸业"),
        ("responsible", "/rɪˈspɒnsəbl/", "adj.", "作为原因的；有责任的"),
        ("responsible for", "/rɪˈspɒnsəbl fɔː(r)/", "phr.", "引起某事；对……负责"),
        ("rapid", "/ˈræpɪd/", "adj.", "迅速的；瞬间的"),
        ("shape", "/ʃeɪp/", "v. / n.", "塑造；形状"),
        ("bronze", "/brɒnz/", "n. & adj.", "青铜（的）；青铜色（的）"),
        ("ware", "/weə(r)/", "n.", "制品；陶器"),
        ("stone", "/stəʊn/", "n.", "石头；岩石"),
        ("jute", "/dʒuːt/", "n.", "黄麻纤维"),
        ("fibre", "/ˈfaɪbə(r)/", "n.", "纤维；纤维素"),
        ("expensive", "/ɪkˈspensɪv/", "adj.", "昂贵的；价格高的"),
        ("officer", "/ˈɒfɪsə(r)/", "n.", "官员；高级职员"),
        ("workshop", "/ˈwɜːkʃɒp/", "n.", "作坊；讲习班"),
        ("none", "/nʌn/", "pron.", "没有一个；毫无"),
        ("ideal", "/aɪˈdiːəl/", "adj. / n.", "最合适的；理想的；理想"),
        ("certain", "/ˈsɜːtn/", "adj. / pron.", "某些；确定的"),
        ("suitable", "/ˈsuːtəbl/", "adj.", "合适的；适宜的"),
        ("liquid", "/ˈlɪkwɪd/", "n. / adj.", "液体；液体的"),
        ("cheap", "/tʃiːp/", "adj. / adv.", "便宜的；低廉地"),
        ("creation", "/kriˈeɪʃn/", "n.", "创造；作品"),
        ("later on", "/ˈleɪtər ɒn/", "phr.", "后来；其后"),
        ("speed up", "/spiːd ʌp/", "phr.", "（使）加速"),
        ("Arabic", "/ˈærəbɪk/", "adj. / n.", "阿拉伯语的；阿拉伯语"),
        ("result in", "/rɪˈzʌlt ɪn/", "phr.", "造成；导致"),
        ("lead to", "/liːd tuː/", "phr.", "导致；造成"),
        ("birth", "/bɜːθ/", "n.", "起源；诞生"),
        ("rapidly", "/ˈræpɪdli/", "adv.", "迅速地；快速地"),
        ("afford", "/əˈfɔːd/", "v.", "买得起；能做"),
        ("company", "/ˈkʌmpəni/", "n.", "公司；剧团"),
        ("sticky", "/ˈstɪki/", "adj.", "黏（性）的；闷热的"),
        ("production", "/prəˈdʌkʃn/", "n.", "生产；制作"),
        ("gradually", "/ˈɡrædʒuəli/", "adv.", "逐渐地；逐步地"),
        ("widely", "/ˈwaɪdli/", "adv.", "广泛地；普遍地"),
        ("be looking to", "", "phr.", "试图找到做某事的方法"),
        ("glider", "/ˈɡlaɪdə(r)/", "n.", "滑翔机"),
        ("Europe", "/ˈjʊərəp/", "n.", "欧洲"),
        ("Lhasa", "/ˈlɑːsə/", "n.", "拉萨（中国城市）"),
        ("Tanggula Pass", "", "n.", "唐古拉山口"),
        ("CE", "/ˌsiː ˈiː/", "n.", "公元"),
    ],
    6: [
        ("beyond", "/bɪˈjɒnd/", "prep. / adv.", "超出；在……较远的一边；在更远处"),
        ("mission", "/ˈmɪʃn/", "n.", "任务；使命"),
        ("telescope", "/ˈtelɪskəʊp/", "n.", "望远镜"),
        ("rover", "/ˈrəʊvə(r)/", "n.", "探测器；漫游者"),
        ("manned", "/mænd/", "adj.", "需人操作的"),
        ("maintain", "/meɪnˈteɪn/", "v.", "维修；保持"),
        ("launch", "/lɔːntʃ/", "v. & n.", "发射；发起"),
        ("weightless", "/ˈweɪtləs/", "adj.", "失重的；无重量的"),
        ("movement", "/ˈmuːvmənt/", "n.", "运动；活动"),
        ("asleep", "/əˈsliːp/", "adj.", "睡着（的）"),
        ("fall asleep", "/fɔːl əˈsliːp/", "phr.", "入睡"),
        ("tie", "/taɪ/", "v. / n.", "系上；束紧；领带"),
        ("geology", "/dʒiˈɒlədʒi/", "n.", "地质；地质学"),
        ("satellite", "/ˈsætəlaɪt/", "n.", "人造卫星；卫星"),
        ("crazy", "/ˈkreɪzi/", "adj.", "疯狂的；不理智的"),
        ("human being", "/ˌhjuːmən ˈbiːɪŋ/", "n.", "人；人类"),
        ("require", "/rɪˈkwaɪə(r)/", "v.", "需要；要求"),
        ("rocket", "/ˈrɒkɪt/", "n.", "火箭"),
        ("cancel", "/ˈkænsl/", "v.", "取消；终止"),
        ("publish", "/ˈpʌblɪʃ/", "v.", "刊登；出版"),
        ("exoplanet", "/ˈeksəʊˌplænɪt/", "n.", "系外行星"),
        ("solar", "/ˈsəʊlə(r)/", "adj.", "太阳的；太阳能的"),
        ("god", "/ɡɒd/", "n.", "神"),
        ("mysterious", "/mɪˈstɪəriəs/", "adj.", "神秘的；奇怪的"),
        ("spacecraft", "/ˈspeɪskrɑːft/", "n. (pl. spacecraft)", "宇宙飞船"),
        ("in case", "/ɪn keɪs/", "phr.", "以防万一"),
        ("board", "/bɔːd/", "n.", "板；牌子"),
        ("on board", "/ɒn bɔːd/", "phr.", "在船（或火车、飞机）上"),
        ("billion", "/ˈbɪljən/", "num.", "十亿"),
        ("trillion", "/ˈtrɪljən/", "num.", "万亿；兆"),
        ("completely", "/kəmˈpliːtli/", "adv.", "彻底地；完全地"),
        ("cooperate", "/kəʊˈɒpəreɪt/", "v.", "合作；协作"),
        ("cooperate with", "/kəʊˈɒpəreɪt wɪð/", "phr.", "合作；协作；配合"),
        ("set foot on", "/set fʊt ɒn/", "phr.", "访问；踏上（某地）"),
        ("galaxy", "/ˈɡæləksi/", "n.", "星系"),
        ("unmanned", "/ˌʌnˈmænd/", "adj.", "无（需）人操作的"),
        ("craft", "/krɑːft/", "n. (pl. craft)", "技艺；工艺；飞行器；船"),
        ("spaceship", "/ˈspeɪsʃɪp/", "n.", "（航天）飞船"),
        ("survey", "/ˈsɜːveɪ/", "n.", "测绘；民意调查"),
        ("crowded", "/ˈkraʊdɪd/", "adj.", "人（太）多的；拥挤的"),
        ("operate", "/ˈɒpəreɪt/", "v.", "操作；运行"),
        ("Mars", "/mɑːz/", "n.", "火星"),
        ("Voyager", "/ˈvɔɪɪdʒə(r)/", "n.", "旅行者号探测器"),
        ("Proxima Centauri", "/ˌprɒksɪmə senˈtɔːri/", "n.", "比邻星"),
    ],
    7: [
        ("rhythm", "/ˈrɪðəm/", "n.", "节奏；韵律"),
        ("folk", "/fəʊk/", "adj. / n.", "民间的；民间音乐；各位"),
        ("traditional", "/trəˈdɪʃənl/", "adj.", "传统的；习俗的"),
        ("pop", "/pɒp/", "n. / v.", "流行音乐；蹦出"),
        ("jazz", "/dʒæz/", "n.", "爵士乐"),
        ("rap", "/ræp/", "n. / v.", "说唱乐；表演说唱乐"),
        ("comment", "/ˈkɒment/", "n. & v.", "评论；批评"),
        ("sing along to", "", "phr.", "随着唱"),
        ("lyric", "/ˈlɪrɪk/", "n. / adj.", "歌词；抒情的"),
        ("electric", "/ɪˈlektrɪk/", "adj.", "电的；令人激动的"),
        ("electric guitar", "/ɪˈlektrɪk ɡɪˈtɑː(r)/", "n.", "电吉他"),
        ("keyboard", "/ˈkiːbɔːd/", "n.", "电子琴；键盘"),
        ("trumpet", "/ˈtrʌmpɪt/", "n.", "小号；喇叭"),
        ("style", "/staɪl/", "n.", "风格；方式"),
        ("performance", "/pəˈfɔːməns/", "n.", "演出；表演"),
        ("golden", "/ˈɡəʊldən/", "adj.", "金色的"),
        ("lover", "/ˈlʌvə(r)/", "n.", "爱好者；情人"),
        ("romantic", "/rəʊˈmæntɪk/", "adj.", "浪漫的；爱情的"),
        ("performer", "/pəˈfɔːmə(r)/", "n.", "演奏者；表演者"),
        ("dance to", "/dɑːns tuː/", "phr.", "随着跳舞"),
        ("purple", "/ˈpɜːpl/", "n. / adj.", "紫色；紫色的"),
        ("poet", "/ˈpəʊɪt/", "n.", "诗人"),
        ("policewoman", "/pəˈliːswʊmən/", "n. (pl. policewomen)", "女警察"),
        ("deaf", "/def/", "adj.", "聋的"),
        ("composer", "/kəmˈpəʊzə(r)/", "n.", "作曲家"),
        ("electronic", "/ɪˌlekˈtrɒnɪk/", "adj.", "电子的"),
        ("download", "/ˌdaʊnˈləʊd/", "v. / n.", "下载；已下载的数据资料"),
        ("rating", "/ˈreɪtɪŋ/", "n.", "评分；等级"),
        ("hats off", "/hæts ɒf/", "phr.", "（向某人）表示敬佩"),
        ("genius", "/ˈdʒiːniəs/", "n.", "天才人物；天赋"),
        ("pianist", "/ˈpɪənɪst/", "n.", "钢琴家；钢琴演奏者"),
        ("gifted", "/ˈɡɪftɪd/", "adj.", "有天赋的"),
        ("outdo", "/ˌaʊtˈduː/", "v. (outdid, outdone)", "胜过"),
        ("widen", "/ˈwaɪdn/", "v.", "拓宽；（使）扩展"),
        ("soul", "/səʊl/", "n.", "真挚情感；灵魂"),
        ("look down on", "/lʊk daʊn ɒn/", "phr.", "轻视；蔑视"),
        ("Polish", "/ˈpəʊlɪʃ/", "adj. / n.", "波兰的；波兰人；波兰语"),
        ("characteristic", "/ˌkærəktəˈrɪstɪk/", "n. / adj.", "特征；品质；典型的；独特的"),
        ("valuable", "/ˈvæljuəbl/", "adj.", "宝贵的；贵重的"),
        ("proudly", "/ˈpraʊdli/", "adv.", "自豪地；壮观地"),
        ("funeral", "/ˈfjuːnərəl/", "n.", "葬礼"),
        ("young and old", "", "phr.", "老老少少"),
        ("profession", "/prəˈfeʃn/", "n.", "职业；行业"),
        ("contribution", "/ˌkɒntrɪˈbjuːʃn/", "n.", "贡献；捐款"),
        ("cartoon", "/kɑːˈtuːn/", "n.", "动画片；漫画"),
        ("fair", "/feə(r)/", "adj. / n.", "公平的；合理的；露天游乐场；集市"),
        ("fair and square", "", "phr.", "光明正大"),
        ("tape", "/teɪp/", "n.", "磁带；录像带"),
        ("tap", "/tæp/", "v. / n.", "用（手指或脚）打节拍；水龙头；轻拍"),
        ("tap one's feet", "", "phr.", "用脚打节拍"),
        ("champion", "/ˈtʃæmpiən/", "n. / v.", "冠军；捍卫"),
        ("finger", "/ˈfɪŋɡə(r)/", "n.", "手指"),
        ("schoolmate", "/ˈskuːlmeɪt/", "n.", "同学"),
        ("nowadays", "/ˈnaʊədeɪz/", "adv.", "现在；目前"),
        ("imagination", "/ɪˌmædʒɪˈneɪʃn/", "n.", "想象力；想象"),
        ("Poland", "/ˈpəʊlənd/", "n.", "波兰"),
        ("Vienna", "/viˈenə/", "n.", "维也纳（奥地利首都）"),
    ],
    8: [
        ("pull-up", "/ˈpʊl ʌp/", "n.", "引体向上"),
        ("relay", "/ˈriːleɪ/", "n.", "接力赛"),
        ("shot-put", "/ˈʃɒt pʊt/", "n.", "推铅球"),
        ("boxing", "/ˈbɒksɪŋ/", "n.", "拳击（运动）"),
        ("competition", "/ˌkɒmpəˈtɪʃn/", "n.", "比赛；竞赛"),
        ("tryout", "/ˈtraɪaʊt/", "n.", "预赛；选拔赛"),
        ("handoff", "/ˈhændɒf/", "n.", "接力棒交接"),
        ("baton", "/ˈbætɒn/", "n.", "接力棒"),
        ("judge", "/dʒʌdʒ/", "n. / v.", "裁判员；法官；判断；认定"),
        ("runner", "/ˈrʌnə(r)/", "n.", "参加赛跑的人"),
        ("advertisement", "/ədˈvɜːtɪsmənt/", "n.", "广告；启事"),
        ("take the lead", "", "phr.", "带头（做某事）"),
        ("smooth", "/smuːð/", "adj.", "顺利的；光滑的"),
        ("make up ground", "", "phr.", "逼近正在向前的人或物"),
        ("catch up with", "/kætʃ ʌp wɪð/", "phr.", "赶上；追上（某人）"),
        ("figure", "/ˈfɪɡə(r)/", "n. / v.", "花样；数字；人物"),
        ("figure skating", "/ˈfɪɡə skeɪtɪŋ/", "n.", "花样滑冰"),
        ("amaze", "/əˈmeɪz/", "v.", "使惊奇；使惊叹"),
        ("strength", "/streŋθ/", "n.", "力量；体力"),
        ("truly", "/ˈtruːli/", "adv.", "真正地；诚恳地"),
        ("anyway", "/ˈeniweɪ/", "adv.", "无论如何；不管怎样"),
        ("ceremony", "/ˈserəməni/", "n.", "典礼；仪式"),
        ("neither", "/ˈnaɪðə(r)/", "conj. & pron.", "也不；两者都不"),
        ("nor", "/nɔː(r)/", "conj. & adv.", "也不"),
        ("neither ... nor ...", "", "phr.", "既不……也不……"),
        ("try out", "/traɪ aʊt/", "phr.", "参加选拔；试用"),
        ("bouldering", "/ˈbəʊldərɪŋ/", "n.", "攀岩"),
        ("compete", "/kəmˈpiːt/", "v.", "参加比赛；竞争"),
        ("mascot", "/ˈmæskət/", "n.", "吉祥物"),
        ("motto", "/ˈmɒtəʊ/", "n.", "口号；格言"),
        ("dramatic", "/drəˈmætɪk/", "adj.", "激动人心的；出乎意料的"),
        ("freestyle", "/ˈfriːstaɪl/", "n.", "自由式体育比赛"),
        ("talented", "/ˈtæləntɪd/", "adj.", "有才能的；天才的"),
        ("in wonder", "/ɪn ˈwʌndə(r)/", "phr.", "惊奇地"),
        ("set a record", "", "phr.", "创造纪录"),
        ("gold", "/ɡəʊld/", "n. / adj.", "金；金牌；金色的"),
        ("medal", "/ˈmedl/", "n.", "奖章；勋章"),
        ("reform", "/rɪˈfɔːm/", "n.", "改革；变革"),
        ("reform and opening-up", "", "n.", "改革开放"),
        ("worldwide", "/ˌwɜːldˈwaɪd/", "adj. / adv.", "世界范围的；在全世界"),
        ("citizen", "/ˈsɪtɪzn/", "n.", "市民；公民"),
        ("pride", "/praɪd/", "n.", "自豪（感）；骄傲"),
        ("harmony", "/ˈhɑːməni/", "n.", "和谐；和睦"),
        ("deeply", "/ˈdiːpli/", "adv.", "非常；极其"),
        ("high point", "", "n.", "最好（或最有意思）的部分"),
        ("master", "/ˈmɑːstə(r)/", "n. / v.", "能手；精通"),
        ("satisfy", "/ˈsætɪsfaɪ/", "v.", "使（某人）满意"),
        ("round", "/raʊnd/", "n.", "比赛阶段；轮次"),
        ("Greek", "/ɡriːk/", "adj. / n.", "希腊的；希腊人；希腊语"),
        ("Roman", "/ˈrəʊmən/", "adj. / n.", "罗马的；罗马人"),
        ("drown", "/draʊn/", "v.", "（使）淹死；溺毙"),
        ("crowd", "/kraʊd/", "n.", "人群；观众"),
        ("Greece", "/ɡriːs/", "n.", "希腊"),
        ("Equatorial Guinea", "/ˌekwəˈtɔːriəl ˈɡɪni/", "n.", "赤道几内亚"),
    ],
}


def all_units():
    return UNITS


def word_count():
    return sum(len(v) for v in UNITS.values())
