#!/usr/bin/env python3
"""
从 HET 词形填空课件 VOCAB_UNITS 中删除初中/中考不考的低频词形。

规则：
- 永不删除 examTarget.form（套题填空考点）
- 删除 denylist / 模式命中的 derivatives 条目
- 同步清理 peers、examExamples、note 中的残留
- 课堂页与 handout 一并处理
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

DIR = Path(__file__).resolve().parents[1] / "HET" / "词形填空练习" / "courseware"

# 明确删除：生造词、学术/超纲派生、中考几乎不考的词形
DENY = {
    # 生造 / 错误
    "childness",
    "childs",
    "possibilist",
    "muchness",
    "otherness",
    "forring",
    "fored",
    "becomer",
    "undifficult",
    "unslow",
    "unsmart",
    "unpressed",
    "unrefusable",
    "missable",
    "unmissable",
    "properize",
    "gradualize",
    "gradualization",
    "colorant",
    "offeree",
    "offerer",
    "reoffer",
    "pollutive",
    "ownable",
    "goalline",
    "goal-oriented",
    "goodly",
    "littleness",
    "neediness",
    "needful",
    # 低频 -ness / 抽象名词
    "childlessness",
    "forgetfulness",
    "truthfulness",
    "inventiveness",
    "worthiness",
    "directness",
    "highness",
    "slowness",
    "badness",
    "luckiness",
    "openness",
    "gradualness",
    "clearness",
    "commonness",
    "fullness",
    "closeness",
    "quickness",
    "smartness",
    "wrongness",
    "shininess",
    "cloudiness",
    "meanness",
    "finality",
    "continuity",
    "actuality",
    "impossibility",
    "productivity",
    "propriety",
    "valuation",
    "specialization",
    "specialty",
    "completion",
    "avoidance",
    "reception",
    "receptive",
    "receipt",
    "inclusion",
    "inclusive",
    "inclusively",
    "exclusive",
    "collective",
    "connective",
    "argumentative",
    "congratulatory",
    "inspirational",
    "preparatory",
    "considerable",
    "considerably",
    "considerate",
    "reconsideration",
    # 低频副词 / -ly 超纲
    "ably",
    "acceptably",
    "avoidably",
    "unavoidably",
    "impossibly",
    "encouragingly",
    "expectantly",
    "forgetfully",
    "movingly",
    "meanly",
    "truthfully",
    "productively",
    "childishly",
    "knowingly",
    "disappointedly",
    "worthily",
    "inventively",
    "influentially",
    "decidedly",
    "surprisedly",
    "understandably",
    "honorably",
    "admirably",
    "restlessly",
    "endlessly",
    "uselessly",
    "colorfully",
    "artistically",
    "creatively",  # creative 保留；creatively 初中较少考
    "creativity",
    # 低频形容词 / 罕见否定
    "expectant",
    "continual",
    "childlike",
    "childless",
    "movable",
    "unmoved",
    "baseless",
    "difficultly",
    "actualize",
    "finalize",
    "finalized",
    "finalizing",
    "finalist",
    "activate",
    "activist",
    "discontinue",
    "unfollow",
    "unforgotten",
    "causal",
    "causally",
    "believer",
    "mover",
    "avoider",
    "giver",
    "solver",
    "refuser",
    "presser",
    "spreader",
    "dropper",
    "passer",
    "teller",
    "saver",
    "flyer",
    "drinker",
    "invitee",
    "protector",
    "colorless",
    "excitable",
    "overexcited",
    "unexcited",
    "unsurprising",
    "unsurprisingly",
    "indecisive",
    "decisive",
    "workable",
    "returnable",
    "non-return",
    "serviceable",
    "passable",
    "touchable",
    "breakable",
    "unbreakable",
    "drinkable",
    "lovable",
    "ownable",
    "misspelling",
    "regrettable",  # 与既有清理一致
    "uninfluential",
    "dissimilar",
    "unenjoyable",
    "undisappointed",
    "unending",
    "unbecoming",
    "uninspired",
    "uninspiring",
    "invaluable",
    "inseparable",
    "indifferent",  # different 词族里塞的超纲项
    "receptive",
    "knowledgeable",
    "goalie",
    "goalless",
    "befriend",
    "friendless",
    "luckless",
    "artless",
    "showy",
    "choosy",
    "runny",
    "runway",
    "gotten",  # 美式，成都中考少见
    "whilst",
    "awhile",
    "one-off",
    "threefold",
    "threesome",
    "thirtieth",
    "triple",
    "nonzero",
    "crosswise",
    "yearling",
    "perennial",
    "yearbook",
    "year-round",
    "yearlong",
    "leap",  # 作为 year 词族噪声
    "annual",  # 初中有时出现；但作为 year 硬塞的派生偏牵强 → 删
    "footwear",
    "footing",
    "moonshine",
    "dropout",
    "droplet",
    "workload",
    "breakdown",
    "breakthrough",
    "follow-up",
    "self-service",
    "firstborn",
    "firsthand",
    "first-class",
    "foremost",
    "uppermost",
    "downcast",
    "downfall",
    "downed",
    "downing",
    "upped",
    "upping",
    "whiled",
    "whiling",
    "while away",
    "pressurized",
    "specialized",
    "specialize",
    "specialist",
    "socialism",
    "socialist",
    "socialize",
    "memorize",
    "memorized",
    "memorizing",
    "to memorize",
    "italianize",
    "popularize",
    "empower",
    "mislead",
    "leadership",
    "ownership",
    "holdings",
    "holder",
    "receiver",
    "developer",  # develop/development 足够
    "underdeveloped",
    "undeveloped",
    "disconnect",
    "rejoin",
    "retell",
    "reuse",
    "rewrite",  # 偶考；但作为 write 硬扩，保留 wrote/written/writing 即可 — 实际 rewrite 有时考，改为保留
    "reinvent",
    "reopen",
    "overspread",
    "unspread",
    "underdone",
    "underwear",  # 作为 under 词族噪声
    "underline",  # 实为独立词，挂在 under 下不合适
    "forbid",  # 挂在 for 下不合适
    "forgive",
    "forget",  # 挂在 for 下
    "caution",  # 挂在 care 下牵强
    "motion",  # move 词族中考更常考 movement/moving
    "properties",  # property 保留
    "appropriate",
    "improper",
    "improperly",
    "dishonor",
    "honorary",
    "wrongdoer",
    "wrongdoing",
    "pollutant",
    "signature",
    "significant",  # 常为独立考点，不宜挂在 sign 下灌输
    "significantly",
    "passage",
    "instructive",
    "instructor",
    "sadden",
    "saddened",
    "smarten",
    "quicken",
    "quickened",
    "quickening",
    "soften",
    "clouded",
    "clouding",
    "cloudless",
    "restful",
    "disinterest",
    "lover",
    "endlessly",
    "unwise",
    "unwisely",
    "outdoor",
    "outdoors",
    "outer",
    "outsider",
    "outward",
    "outwards",
    "downward",
    "downwards",
    "upward",
    "upwards",
    "sideways",
    "inability",
    "disability",
    "enabled",
    "acceptably",
    "usage",
    "uselessly",
    "user",
    "continuation",
    "continually",
    "to continue",
    "To continue",
    "To show",
    "to surprise",
    "to avoid",
    "to follow",
    "to complete",
    "to tell",
    "to get",
    "to understand",
    "to enjoy",
    "to offer",
    "to join",
    "to hold",
    "to drink",
    "to rain",
    "to return",
    "to congratulate",
    "to inspire",
    "to create",
    "to show",
    "more possible",
    "most possible",
    "more complete",
    "more special",
    "most special",
    "more total",
    "more valuable",
    "most valuable",
    "more social",
    "more common",
    "most common",
    "more gradually",
    "most gradually",
    "more powerful",
    "had expected",
    "be forgotten",
    "be given",
    "was given",
    "was accepted",
    "was written",
    "was touched",
    "was solved",
    "was divided",
    "was encouraged",
    "were encouraged",
    "were received",
    "were told",
    "are connected",
    "are filled",
    "are invited",
    "has run",
    "has stuck",
    "has honored",
    "haven't lost",
    "have become",
    "Moved",
    "Slowly",
    "Finally",
    "Encouraging",
    "they'd",
    "they'll",
    "they're",
    "we'd",
    "we'll",
    "she'd",
    "she'll",
    "she's",
    "but for",
    "buts",
    "cannot but",
    "not only...but also...",
    "merely",
    "except",
    "however",
    "since",
    "cause",
    "caused",
    "causes",
    "causing",
    "threes",
    "thirteen",
    "thirdly",
    "one's",
    "one-way",
    "ones",
    "someone",
    "only",
    "firstly",
    "once",
    "raindrop",
    "rainfall",
}

# 从 DENY 中移出应保留的中考常见项（防止误伤）
KEEP_OVERRIDE = {
    "enable",
    "disabled",
    "unable",
    "ability",
    "abilities",
    "acceptable",
    "unacceptable",
    "acceptance",
    "possibility",
    "possibilities",
    "possibly",
    "impossible",
    "otherwise",
    "excitement",
    "excitedly",
    "disappointment",
    "correction",
    "incorrect",
    "correctness",  # 较少但仍可见
    "comfortably",
    "uncomfortable",
    "uncomfortably",
    "movement",
    "moving",
    "moved",
    "moves",
    "chose",
    "chosen",
    "gave",
    "given",
    "gives",
    "giving",
    "knew",
    "known",
    "unknown",
    "knowledge",
    "wrote",
    "written",
    "writing",
    "writer",
    "writers",
    "writes",
    "flew",
    "flown",
    "flight",
    "spoke",
    "spoken",
    "told",  # tell 的过去式要保留；get 下的会用 HEAD_DENY
    "unexpected",
    "unexpectedly",
    "expectation",
    "successful",
    "successfully",
    "unsuccessful",
    "success",
    "succeed",
    "prevention",
    "preventive",
    "discourage",
    "encouragement",
    "encouraging",
    "encouraged",
    "regretful",
    "regretfully",
    "regrettably",
    "useless",
    "useful",
    "incomplete",
    "unluckily",
    "luckily",
    "unlucky",
    "lucky",
    "meanwhile",
    "nowhere",
    "widen",
    "widely",
    "width",
    "actively",
    "activity",
    "actions",
    "action",
    "active",
    "actor",
    "actress",
    "football",
    "footstep",
    "footprint",
    "continuous",
    "continuously",
    "continued",
    "continues",
    "continuing",
    "forgetful",
    "unforgettable",
    "forgot",
    "forgotten",
    "forgetting",
    "forgets",
    "truth",
    "truths",
    "truly",
    "truthful",
    "untrue",
    "careful",
    "carefully",
    "careless",
    "carelessly",
    "carelessness",
    "meaningful",
    "meaningless",
    "meaning",
    "meanings",
    "means",
    "meant",
    "meantime",
    "avoidable",
    "unavoidable",
    "avoided",
    "avoiding",
    "product",
    "production",
    "producer",
    "produced",
    "produces",
    "producing",
    "productive",
    "followed",
    "following",
    "follows",
    "follower",
    "followers",
    "third",
    "alive",
    "life",
    "lived",
    "lives",
    "living",
    "lively",
    "finally",
    "final",
    "finals",
    "valuable",
    "valued",
    "values",
    "believe",
    "believed",
    "believes",
    "believing",
    "believable",
    "unbelievable",
    "unbelievably",
    "belief",
    "appearance",
    "appeared",
    "appearing",
    "appears",
    "disappear",
    "disappearance",
    "disappeared",
    "disappearing",
    "friendship",
    "friendly",
    "unfriendly",
    "friends",
    "friendlier",
    "friendliest",
    "excited",
    "exciting",
    "decision",
    "decided",
    "decides",
    "deciding",
    "surprised",
    "surprising",
    "surprisingly",
    "worker",
    "working",
    "worked",
    "works",
    "workshop",
    "colorful",
    "colored",
    "colors",
    "coloring",
    "quickly",
    "quicker",
    "quickest",
    "consideration",
    "considered",
    "considering",
    "connection",
    "connected",
    "connecting",
    "connects",
    "goalkeeper",
    "goals",
    "commonly",
    "uncommon",
    "freedom",
    "freely",
    "helpful",
    "helpless",
    "helper",
    "helped",
    "helping",
    "helps",
    "creation",
    "creative",
    "creator",
    "creating",
    "pressure",
    "pressed",
    "pressing",
    "presses",
    "rainbow",
    "rainy",
    "rained",
    "raining",
    "rains",
    "closely",
    "closed",
    "closer",
    "closest",
    "closing",
    "closes",
    "difference",
    "differently",
    "differ",
    "invention",
    "invented",
    "inventing",
    "inventor",
    "directly",
    "direction",
    "director",
    "indirect",
    "indirectly",
    "feet",
    "collection",
    "collector",
    "collected",
    "collecting",
    "collects",
    "difficulty",
    "difficulties",
    "powerful",
    "powerless",
    "powers",
    "powerfully",
    "understanding",
    "understood",
    "understandable",
    "misunderstanding",
    "held",
    "holding",
    "holds",
    "argument",
    "arguments",
    "argued",
    "argues",
    "arguing",
    "better",
    "best",
    "well",
    "goodness",
    "goods",
    "underground",
    "underneath",
    "understand",
    "shining",
    "shiny",
    "shone",
    "sunshine",
    "touched",
    "touches",
    "touching",
    "untouched",
    "leader",
    "leading",
    "leads",
    "led",
    "solution",
    "solved",
    "solving",
    "unsolved",
    "noticeable",
    "noticeably",
    "noticed",
    "notices",
    "noticing",
    "unnoticed",
    "kindness",
    "kindly",
    "kinder",
    "kindest",
    "unkind",
    "returned",
    "returning",
    "returns",
    "served",
    "serviced",
    "services",
    "servicing",
    "owner",
    "owners",
    "owned",
    "owning",
    "thorough",
    "thoroughly",
    "throughout",
    "loser",
    "loses",
    "losing",
    "loss",
    "lost",
    "joined",
    "joining",
    "joins",
    "joint",
    "snowy",
    "snowman",
    "snowflake",
    "snowed",
    "snowing",
    "snows",
    "dead",
    "death",
    "died",
    "dies",
    "dying",
    "deadly",
    "dropped",
    "dropping",
    "drops",
    "influential",
    "influenced",
    "influences",
    "influencing",
    "interest",
    "interested",
    "interestingly",
    "interests",
    "uninteresting",
    "loved",
    "lovely",
    "loves",
    "loving",
    "ended",
    "ending",
    "endless",
    "ends",
    "wisdom",
    "wisely",
    "wiser",
    "wisest",
    "became",
    "becomes",
    "becoming",
    "smarter",
    "smartest",
    "smartly",
    "spreading",
    "spreads",
    "widespread",
    "rested",
    "resting",
    "restless",
    "rests",
    "gradual",
    "gradually",
    "congratulated",
    "congratulating",
    "congratulation",
    "congratulations",
    "instruct",
    "instructed",
    "instructing",
    "instructions",
    "invitation",
    "invited",
    "invites",
    "inviting",
    "sadly",
    "sadness",
    "sadder",
    "saddest",
    "showed",
    "showing",
    "shown",
    "shows",
    "inspiration",
    "inspired",
    "inspiring",
    "passed",
    "passes",
    "passing",
    "signed",
    "signing",
    "signs",
    "polluted",
    "pollutes",
    "polluting",
    "pollution",
    "refusal",
    "refused",
    "refuses",
    "refusing",
    "separated",
    "separately",
    "separates",
    "separating",
    "separation",
    "honorable",
    "honored",
    "broke",
    "broken",
    "breaking",
    "reasonable",
    "reasonably",
    "reasoned",
    "reasoning",
    "reasons",
    "unreasonable",
    "divided",
    "dividing",
    "division",
    "undivided",
    "sticker",
    "sticking",
    "sticks",
    "sticky",
    "stuck",
    "admirable",
    "admiration",
    "admired",
    "admiring",
    "social",
    "socially",
    "society",
    "first",
    "cloudy",
    "clouds",
    "upper",
    "protected",
    "protecting",
    "protection",
    "protective",
    "protects",
    "memorable",
    "memories",
    "memory",
    "artist",
    "artistic",
    "artists",
    "artwork",
    "smoothed",
    "smoother",
    "smoothes",
    "smoothest",
    "smoothing",
    "smoothly",
    "softened",
    "softer",
    "softest",
    "softly",
    "softness",
    "wronged",
    "wronging",
    "wrongly",
    "safe",
    "safely",
    "safety",
    "saved",
    "savings",
    "basement",  # 课标词，basic 词族可留
    "based",
    "basically",
    "basics",
    "base",
    "needless",  # 常见
    "childhood",
    "childish",
    "children",
    "children's",
    "actor",
    "actress",
    "yearly",
    "years",
    "year's",
    "gift",  # give→gift 常考
    "gifts",
    "rewrite",
    "rainier",
    "property",
    "properly",
    "specially",
    "completely",
    "completed",
    "completes",
    "completing",
    "because of",
    "another",
    "others",
    "the other",
    "the others",
    "each other",
    "ours",
    "ourselves",
    "our",
    "us",
    "their",
    "theirs",
    "them",
    "themselves",
    "her",
    "hers",
    "herself",
    "him",
    "his",
    "himself",
    "itself",
    "myself",
    "yourself",
    "yourselves",
    "oneself",
    "a little",
    "a few",
    "less",
    "least",
    "littler",
    "littlest",
    "instead of",
    "more difficult",
    "most difficult",
    "enable",
    "meanwhile",
    "alive",
    "told",
}

# 特定 headword 下额外删除（错误挂靠 / 超纲灌输）
HEAD_DENY = {
    "get": {"told", "were told"},
    "for": {"forbid", "forbidden", "fored", "forget", "forgive", "forring"},
    "under": {"underdone", "underwear", "underline", "understand"},
    "care": {"caution"},
    "because": {"causal", "causally", "cause", "caused", "causes", "causing", "since"},
    "but": {"but for", "buts", "cannot but", "except", "however", "merely", "not only...but also..."},
    "one": {"one-off", "one-way", "one's", "ones", "someone", "only", "firstly", "once", "first"},
    "three": {"threefold", "threesome", "thirtieth", "thirteen", "threes", "triple"},
    "year": {"annual", "leap", "perennial", "year-round", "yearbook", "yearling", "yearlong"},
    "while": {"awhile", "whilst", "while away", "whiled", "whiling"},
    "down": {"downcast", "downed", "downfall", "downing", "downs"},
    "up": {"upped", "upping", "uppermost"},
    "through": {"breakthrough", "get through", "go through"},
    "outside": {"outdoor", "outdoors", "outer", "outsider", "outward", "outwards"},
    "sign": {"signature", "significant", "significantly"},
    "different": {"indifferent", "parts"},
    "open": {"closed"},
    "good": {"goodly"},
    "little": {"littleness"},
    "much": {"muchness"},
    "other": {"otherness"},
    "possible": {"possibilist", "impossibility", "impossibly", "more possible", "most possible"},
    "able": {"ably", "inability", "acceptably"},
    "true": {"truer", "truest", "truthfully", "truthfulness"},
    "mean": {"meanly", "meanness"},
    "expect": {"expectant", "expectantly"},
    "avoid": {"avoidably", "avoidance", "avoider", "unavoidably"},
    "move": {"movable", "mover", "movingly", "unmoved", "motion"},
    "forget": {"forgetfully", "forgetfulness", "unforgotten"},
    "continue": {"continual", "continually", "continuation", "continuity", "discontinue", "To continue", "to continue"},
    "produce": {"productively", "productivity"},
    "accept": {"acceptably"},
    "follow": {"unfollow", "follow-up"},
    "child": {"childness", "childs", "childlessness", "childishly", "childlike", "childless"},
    "special": {"specialize", "specialized", "specialization", "specialty", "specialist", "more special", "most special"},
    "final": {"finalist", "finality", "finalize", "finalized", "finalizing"},
    "complete": {"completion", "more complete"},
    "luck": {"luckiness", "luckless"},
    "proper": {"properize", "propriety", "properties", "appropriate", "improper", "improperly"},
    "value": {"valuation", "invaluable", "more valuable", "most valuable"},
    "belief": {"believer"},
    "encourage": {"encouragingly"},
    "friend": {"befriend", "friendless"},
    "excite": {"excitable", "overexcited", "unexcited"},
    "receive": {"receipt", "receiver", "reception", "receptive"},
    "regret": {"regrettable"},
    "decide": {"decidedly", "decisive", "indecisive"},
    "surprise": {"surprisedly", "unsurprising", "unsurprisingly", "to surprise"},
    "work": {"workable", "workload"},
    "color": {"colorant", "colorless", "colorfully"},
    "quick": {"quicken", "quickened", "quickening", "quickness"},
    "consider": {"considerable", "considerably", "considerate", "reconsideration"},
    "include": {"exclusive", "inclusion", "inclusive", "inclusively"},
    "clear": {"clearness"},
    "tell": {"teller"},
    "enjoy": {"unenjoyable"},
    "offer": {"offeree", "offerer", "reoffer"},
    "run": {"runny", "runway", "gotten"},
    "prepare": {"preparatory"},
    "full": {"fullness", "are filled"},
    "develop": {"developer", "underdeveloped", "undeveloped"},
    "connect": {"connective", "disconnect"},
    "goal": {"goalie", "goalless", "goalline", "goal-oriented", "goal's"},
    "know": {"knowingly", "knowledgeable"},
    "common": {"commonness"},
    "create": {"creatively", "creativity"},
    "press": {"presser", "pressurized", "unpressed"},
    "drink": {"drinkable", "drinker"},
    "close": {"closeness"},
    "invent": {"inventively", "reinvent", "inventiveness"},
    "correct": {"correctness"},
    "disappoint": {"disappointedly", "undisappointed"},
    "direct": {"directness"},
    "foot": {"footwear", "footing"},
    "miss": {"missable", "unmissable", "misspelling"},
    "difficult": {"difficultly", "undifficult"},
    "fly": {"flyer"},
    "power": {"empower"},
    "understand": {"understandably"},
    "hold": {"holder", "holdings"},
    "argue": {"argumentative"},
    "shine": {"moonshine", "shininess"},
    "touch": {"touchable"},
    "lead": {"leadership", "mislead"},
    "solve": {"solver"},
    "choose": {"choosy"},
    "return": {"returnable", "non-return"},
    "service": {"serviceable", "self-service"},
    "own": {"ownable", "ownership"},
    "lose": {"haven't lost"},
    "drop": {"droplet", "dropout", "dropper"},
    "influence": {"influentially", "uninfluential"},
    "interesting": {"disinterest"},
    "love": {"lovable", "lover"},
    "end": {"endlessly", "unending"},
    "wise": {"unwise", "unwisely"},
    "become": {"becomer", "unbecoming", "have become"},
    "smart": {"smarten", "smartness", "unsmart"},
    "spread": {"overspread", "spreader", "unspread"},
    "rest": {"restful", "restlessly"},
    "gradually": {"gradualize", "gradualization", "gradualness", "more gradually", "most gradually"},
    "congratulate": {"congratulatory"},
    "instruction": {"instructive", "instructor"},
    "invite": {"invitee", "are invited"},
    "sad": {"sadden", "saddened"},
    "show": {"showy", "To show"},
    "inspire": {"inspirational", "uninspired", "uninspiring"},
    "pass": {"passable", "passer", "passage"},
    "pollute": {"pollutant", "pollutive"},
    "refuse": {"refuser", "unrefusable"},
    "separate": {"inseparable"},
    "honor": {"dishonor", "honorably", "honorary", "has honored"},
    "break": {"breakable", "unbreakable", "breakdown"},
    "divide": {"divider"},
    "admire": {"admirably"},
    "society": {"socialism", "socialist", "socialize", "more social"},
    "first": {"first-class", "firstborn", "firsthand", "foremost", "firsts"},
    "cloud": {"clouded", "cloudiness", "clouding", "cloudless"},
    "protect": {"protector"},
    "memory": {"memorize", "memorized", "memorizing", "to memorize"},
    "art": {"artless", "artistically"},
    "wrong": {"wrongdoer", "wrongdoing", "wrongness"},
    "save": {"saver"},
    "use": {"usage", "uselessly", "user", "reuse"},
    "slow": {"slowness", "unslow"},
    "succeed": {"unsuccessfully"},
    "success": {"unsuccessfully"},
    "need": {"needful", "neediness"},
    "zero": {"nonzero"},
    "basic": {"baseless"},
    "actual": {"actualize", "actuality"},
    "across": {"crosswise"},
    "worth": {"worthily", "worthiness"},
    "write": {"was written"},
    "give": {"be given", "was given", "giver"},
    "act": {},  # 多数可留
    "rain": {"raindrop", "rainfall"},
    "total": {"more total", "totaled", "totaling", "totalled", "totalling"},
    "free": {"freed", "freeing", "frees"},
    "help": {"to help"},
    "live": {"livelier", "liveliest"},
    "they": {"they'd", "they'll", "they're"},
    "we": {"we'd", "we'll"},
    "she": {"she'd", "she'll", "she's"},
}

# 模式：整词匹配后删除（不区分大小写）
DENY_PATTERNS = [
    re.compile(r"^(to|To)\s+[a-zA-Z]+$"),  # to V / To V
    re.compile(r"^(was|were|are|be|has|have|had|haven't)\s+", re.I),
    re.compile(r"^more\s+", re.I),
    re.compile(r"^most\s+", re.I),
    re.compile(r"ize$"),
    re.compile(r"izing$"),
    re.compile(r"ized$"),
    re.compile(r"isation$"),
    re.compile(r"ization$"),
]

# 模式删除的例外（realize/organize 等课标 -ize）
PATTERN_KEEP = {
    "realize",
    "realized",
    "realizing",
    "organize",
    "organized",
    "organizing",
    "organization",
    "apologize",
    "apologized",
    "apologizing",
    "surprise",
    "surprised",
    "surprising",
    "prize",
    "size",
}


def norm(s: str) -> str:
    return (s or "").strip()


def should_remove(answer: str, headword: str, exam_form: str) -> bool:
    a = norm(answer)
    if not a:
        return True
    al = a.lower()
    ef = norm(exam_form).lower()
    if ef and al == ef:
        return False
    if al in KEEP_OVERRIDE or a in KEEP_OVERRIDE:
        return False
    hw = (headword or "").lower()
    if al in {x.lower() for x in HEAD_DENY.get(hw, set())}:
        return True
    if al in DENY or a in DENY:
        return True
    if al in PATTERN_KEEP:
        return False
    for pat in DENY_PATTERNS:
        if pat.search(a) or pat.search(al):
            return True
    return False


def clean_note(note: str, removed: set[str]) -> str:
    if not note:
        return note
    out = note
    for r in sorted(removed, key=len, reverse=True):
        out = re.sub(re.escape(r), "", out, flags=re.I)
    out = re.sub(r"\s{2,}", " ", out)
    out = re.sub(r"\s+,", ",", out)
    out = re.sub(r",\s*,+", ",", out)
    out = re.sub(r"（\s*）|\(\s*\)", "", out)
    out = re.sub(r"/\s*/", "/", out)
    out = re.sub(r"、\s*、", "、", out)
    return out.strip(" ，、/|;")


def prune_unit(unit: dict) -> tuple[int, int]:
    """Returns (removed_derivs, removed_examples)."""
    hw = unit.get("headword") or ""
    et = unit.get("examTarget") or {}
    exam_form = et.get("form") or ""
    removed_answers: set[str] = set()

    derivs = unit.get("derivatives") or []
    kept = []
    for d in derivs:
        ans = norm(d.get("answer") or "")
        if should_remove(ans, hw, exam_form):
            removed_answers.add(ans)
            removed_answers.add(ans.lower())
            continue
        # clean peers
        induct = d.get("induct") or {}
        peers = induct.get("peers")
        if isinstance(peers, list):
            induct["peers"] = [
                p
                for p in peers
                if not should_remove(norm(p), hw, exam_form) and norm(p).lower() not in {x.lower() for x in removed_answers}
            ]
            d["induct"] = induct
        kept.append(d)
    unit["derivatives"] = kept

    # second pass: peers may still contain forms removed in sibling entries
    ban = {x.lower() for x in removed_answers}
    for d in unit["derivatives"]:
        induct = d.get("induct") or {}
        peers = induct.get("peers")
        if isinstance(peers, list):
            induct["peers"] = [p for p in peers if norm(p).lower() not in ban and not should_remove(norm(p), hw, exam_form)]
            d["induct"] = induct

    rem_ex = 0
    if et:
        examples = et.get("examExamples") or []
        new_ex = []
        for ex in examples:
            ba = norm(ex.get("blankAnswer") or "")
            if ba and should_remove(ba, hw, exam_form) and ba.lower() != norm(exam_form).lower():
                rem_ex += 1
                removed_answers.add(ba)
                continue
            new_ex.append(ex)
        et["examExamples"] = new_ex
        if et.get("note"):
            et["note"] = clean_note(et["note"], removed_answers)
        unit["examTarget"] = et

    return len(derivs) - len(kept), rem_ex


def extract_array_span(html: str, name: str) -> tuple[int, int, str] | None:
    marker = f"const {name} = "
    start = html.find(marker)
    if start < 0:
        return None
    i = start + len(marker)
    while i < len(html) and html[i].isspace():
        i += 1
    if i >= len(html) or html[i] != "[":
        return None
    depth = 0
    j = i
    in_str = False
    esc = False
    quote = ""
    while j < len(html):
        c = html[j]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == quote:
                in_str = False
        else:
            if c in "\"'":
                in_str = True
                quote = c
            elif c == "[":
                depth += 1
            elif c == "]":
                depth -= 1
                if depth == 0:
                    return start, j + 1, html[i : j + 1]
        j += 1
    return None


def format_units(units: list, indent: int = 4) -> str:
    pad = " " * indent
    body = json.dumps(units, ensure_ascii=False, indent=4)
    # indent each line to match original style (const VOCAB_UNITS =     [\n        {)
    lines = body.split("\n")
    # body already starts with [ ; we want leading spaces before [
    # Original uses: const VOCAB_UNITS =     [\n        {
    formatted = "\n".join(pad + line if idx > 0 else line for idx, line in enumerate(lines))
    # The assignment leaves spaces before [: keep "    " + formatted after "= "
    return formatted


def process_file(path: Path, dry: bool = False) -> dict:
    html = path.read_text(encoding="utf-8")
    span = extract_array_span(html, "VOCAB_UNITS")
    if not span:
        return {"file": path.name, "skipped": True}
    assign_start, end, raw = span
    units = json.loads(raw)
    rem_d = rem_e = 0
    for u in units:
        d, e = prune_unit(u)
        rem_d += d
        rem_e += e
    # rebuild: keep "const VOCAB_UNITS = " and original spacing before [
    marker = "const VOCAB_UNITS = "
    i = assign_start + len(marker)
    while i < end and html[i].isspace():
        i += 1
    # spaces between = and [
    spaces = html[assign_start + len(marker) : i]
    new_array = format_units(units, indent=4)
    # format_units returns from "[" with subsequent lines indented by 4;
    # first line is "[" — add nothing; match original which had content at indent 8 for objects.
    # Actually json.dumps indent=4 then we add pad=4 to lines after first → objects at 8 spaces. Good.
    new_html = html[: assign_start + len(marker)] + spaces + new_array + html[end:]
    if not dry:
        path.write_text(new_html, encoding="utf-8")
    return {
        "file": path.name,
        "units": len(units),
        "removed_derivatives": rem_d,
        "removed_examples": rem_e,
        "skipped": False,
    }


def main():
    dry = "--dry" in sys.argv
    files = sorted(DIR.glob("*选词填空*.html"))
    files = [f for f in files if "vocab-drill" not in f.name]
    total_d = total_e = 0
    n = 0
    for f in files:
        r = process_file(f, dry=dry)
        if r.get("skipped"):
            print(f"SKIP {r['file']}")
            continue
        n += 1
        total_d += r["removed_derivatives"]
        total_e += r["removed_examples"]
        print(
            f"{'[DRY] ' if dry else ''}"
            f"{r['file']}: -{r['removed_derivatives']} derivs, -{r['removed_examples']} examples"
        )
    print(f"\nDone. files={n} removed_derivatives={total_d} removed_examples={total_e} dry={dry}")


if __name__ == "__main__":
    main()
